import { ArborError } from "./errors.js";
import type {
  AttemptState,
  AuthorizationState,
  CleanupState,
  EffectState,
  ExplorationPhase,
  GateState,
  HypothesisState,
  PromotionState,
  ReportState,
  RunState,
} from "./types.js";

export type TransitionTable<S extends string> = Readonly<Record<S, ReadonlySet<S>>>;
const set = <S extends string>(...states: S[]): ReadonlySet<S> => new Set(states);

const activeRunStates: RunState[] = ["ADMITTED", "BASELINING", "EXPLORING", "VERIFYING_FINAL", "AWAITING_PROMOTION", "PROMOTING"];

const runMutable: Record<RunState, Set<RunState>> = {
  STAGED: new Set(["ADMITTED"]),
  ADMITTED: new Set(["BASELINING", "WAITING_INPUT", "PAUSED", "CANCELLING", "FAILED", "INDETERMINATE", "QUARANTINED"]),
  BASELINING: new Set(["EXPLORING", "WAITING_INPUT", "PAUSED", "CANCELLING", "FAILED", "INDETERMINATE", "QUARANTINED"]),
  EXPLORING: new Set(["VERIFYING_FINAL", "COMPLETED", "WAITING_INPUT", "PAUSED", "CANCELLING", "FAILED", "INDETERMINATE", "QUARANTINED"]),
  VERIFYING_FINAL: new Set(["AWAITING_PROMOTION", "COMPLETED", "WAITING_INPUT", "PAUSED", "CANCELLING", "FAILED", "INDETERMINATE", "QUARANTINED"]),
  AWAITING_PROMOTION: new Set(["PROMOTING", "COMPLETED", "WAITING_INPUT", "PAUSED", "CANCELLING", "FAILED", "INDETERMINATE", "QUARANTINED"]),
  PROMOTING: new Set(["COMPLETED", "WAITING_INPUT", "PAUSED", "CANCELLING", "FAILED", "INDETERMINATE", "QUARANTINED"]),
  COMPLETED: new Set(["REPORT_PENDING", "CLEANUP_PENDING", "ROLLBACK_REQUESTED"]),
  WAITING_INPUT: new Set([...activeRunStates, "CANCELLING", "FAILED", "INDETERMINATE", "QUARANTINED"]),
  PAUSED: new Set([...activeRunStates, "CANCELLING", "FAILED", "INDETERMINATE", "QUARANTINED"]),
  CANCELLING: new Set(["CANCELLED", "INDETERMINATE", "QUARANTINED"]),
  CANCELLED: new Set(["REPORT_PENDING", "CLEANUP_PENDING"]),
  FAILED: new Set(["REPORT_PENDING", "CLEANUP_PENDING"]),
  INDETERMINATE: new Set(["REPORT_PENDING"]),
  QUARANTINED: new Set(["REPORT_PENDING"]),
  REPORT_PENDING: new Set(["COMPLETED", "CANCELLED", "FAILED", "INDETERMINATE", "QUARANTINED", "ROLLED_BACK"]),
  CLEANUP_PENDING: new Set(["COMPLETED", "CANCELLED", "FAILED", "ROLLED_BACK", "INDETERMINATE"]),
  ROLLBACK_REQUESTED: new Set(["ROLLING_BACK", "QUARANTINED"]),
  ROLLING_BACK: new Set(["ROLLED_BACK", "QUARANTINED"]),
  ROLLED_BACK: new Set(["AWAITING_PROMOTION", "REPORT_PENDING", "CLEANUP_PENDING"]),
};
export const RUN_TRANSITIONS: TransitionTable<RunState> = runMutable;

export const EXPLORATION_TRANSITIONS: TransitionTable<ExplorationPhase> = {
  OBSERVE: set("IDEATE", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  IDEATE: set("SELECT", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  SELECT: set("PREPARE", "FINALIZE_RUN", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  PREPARE: set("DISPATCH", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  DISPATCH: set("COLLECT", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  COLLECT: set("FINALIZE", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  FINALIZE: set("EVALUATE_DEV", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  EVALUATE_DEV: set("BACKPROPAGATE", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  BACKPROPAGATE: set("DECIDE", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  DECIDE: set("OBSERVE", "VERIFY_CANDIDATE", "FINALIZE_RUN", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  VERIFY_CANDIDATE: set("FINALIZE_RUN", "RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  FINALIZE_RUN: set("RECONCILING", "WAITING_INPUT", "PAUSED", "CANCELLING", "INDETERMINATE", "QUARANTINED"),
  RECONCILING: set("OBSERVE", "IDEATE", "SELECT", "PREPARE", "DISPATCH", "COLLECT", "FINALIZE", "EVALUATE_DEV", "BACKPROPAGATE", "DECIDE", "VERIFY_CANDIDATE", "FINALIZE_RUN", "INDETERMINATE", "QUARANTINED"),
  WAITING_INPUT: set("OBSERVE", "IDEATE", "SELECT", "PREPARE", "DISPATCH", "COLLECT", "FINALIZE", "EVALUATE_DEV", "BACKPROPAGATE", "DECIDE", "VERIFY_CANDIDATE", "FINALIZE_RUN", "CANCELLING"),
  PAUSED: set("OBSERVE", "IDEATE", "SELECT", "PREPARE", "DISPATCH", "COLLECT", "FINALIZE", "EVALUATE_DEV", "BACKPROPAGATE", "DECIDE", "VERIFY_CANDIDATE", "FINALIZE_RUN", "CANCELLING"),
  CANCELLING: set("INDETERMINATE", "QUARANTINED"),
  INDETERMINATE: set(),
  QUARANTINED: set(),
};

export const GATE_TRANSITIONS: TransitionTable<GateState> = {
  OPEN: set("ANSWERED", "EXPIRED", "REJECTED"),
  ANSWERED: set(),
  EXPIRED: set(),
  REJECTED: set(),
};

export const HYPOTHESIS_TRANSITIONS: TransitionTable<HypothesisState> = {
  PROPOSED: set("PENDING", "PRUNED", "CANCELLED"),
  PENDING: set("SELECTED", "PRUNED", "CANCELLED"),
  SELECTED: set("RUNNING", "PRUNED", "CANCELLED"),
  RUNNING: set("CANDIDATE", "RETRYABLE", "FAILED", "INTERRUPTED", "PRUNED", "CANCELLED"),
  CANDIDATE: set("VERIFYING_HELD_OUT", "PRUNED", "CANCELLED"),
  RETRYABLE: set("SELECTED", "PRUNED", "CANCELLED"),
  FAILED: set(),
  INTERRUPTED: set("RECONCILING", "CANCELLED"),
  RECONCILING: set("RUNNING", "RETRYABLE", "CANDIDATE", "INDETERMINATE", "CANCELLED"),
  INDETERMINATE: set(),
  VERIFYING_HELD_OUT: set("VERIFIED", "REJECTED", "QUARANTINED"),
  VERIFIED: set("PROMOTABLE"),
  REJECTED: set(),
  QUARANTINED: set(),
  PROMOTABLE: set("PROMOTED", "STALE_BASE", "PRUNED", "CANCELLED"),
  PROMOTED: set("ROLLED_BACK"),
  STALE_BASE: set("VERIFYING_HELD_OUT", "PRUNED", "CANCELLED"),
  ROLLED_BACK: set("PROMOTABLE"),
  PRUNED: set(),
  CANCELLED: set(),
};

export const ATTEMPT_TRANSITIONS: TransitionTable<AttemptState> = {
  RESERVED: set("PREPARING", "CANCELLED"),
  PREPARING: set("READY", "INTERRUPTED"),
  READY: set("DISPATCHING", "CANCELLED"),
  DISPATCHING: set("RUNNING", "INTERRUPTED"),
  RUNNING: set("COLLECTING", "INTERRUPTED"),
  COLLECTING: set("FINALIZING", "INTERRUPTED"),
  FINALIZING: set("CANDIDATE", "REJECTED", "INTERRUPTED"),
  CANDIDATE: set(),
  REJECTED: set(),
  INTERRUPTED: set("RECONCILING"),
  RECONCILING: set("READY", "RUNNING", "COLLECTING", "FINALIZING", "PARTIAL", "RETRYABLE", "CANCELLED", "INDETERMINATE"),
  PARTIAL: set(),
  RETRYABLE: set("RETRIED"),
  CANCELLED: set(),
  INDETERMINATE: set(),
  RETRIED: set(),
};

export const EFFECT_TRANSITIONS: TransitionTable<EffectState> = {
  INTENDED: set("DISPATCHING", "STARTED", "OBSERVING", "OBSERVED", "FAILED_ABSENT", "FAILED", "INDETERMINATE", "CANCEL_REQUESTED"),
  DISPATCHING: set("STARTED", "OBSERVING", "FAILED_ABSENT", "FAILED", "INDETERMINATE", "CANCEL_REQUESTED"),
  STARTED: set("OBSERVING", "OBSERVED", "FAILED", "INDETERMINATE", "CANCEL_REQUESTED"),
  OBSERVING: set("OBSERVED", "FAILED_ABSENT", "FAILED", "INDETERMINATE", "CANCEL_REQUESTED"),
  OBSERVED: set("COMMITTED", "FAILED", "INDETERMINATE"),
  COMMITTED: set(),
  FAILED_ABSENT: set(),
  FAILED: set(),
  INDETERMINATE: set(),
  CANCEL_REQUESTED: set("CANCELLED_CONFIRMED", "INDETERMINATE"),
  CANCELLED_CONFIRMED: set(),
};

export const PROMOTION_TRANSITIONS: TransitionTable<PromotionState> = {
  REQUESTED: set("PREPARING", "REJECTED", "STALE_BASE", "INDETERMINATE"),
  PREPARING: set("CANDIDATE_BUILT", "REJECTED", "STALE_BASE", "INDETERMINATE"),
  CANDIDATE_BUILT: set("VERIFYING", "REJECTED", "STALE_BASE", "INDETERMINATE"),
  VERIFYING: set("PREPARED", "REJECTED", "STALE_BASE", "INDETERMINATE"),
  PREPARED: set("AWAITING_AUTHORIZATION", "REJECTED", "STALE_BASE", "INDETERMINATE"),
  AWAITING_AUTHORIZATION: set("AWAITING_FABRIC_POLICY", "REJECTED", "STALE_BASE", "INDETERMINATE"),
  AWAITING_FABRIC_POLICY: set("COMMIT_PLANNED", "REJECTED", "STALE_BASE", "INDETERMINATE"),
  COMMIT_PLANNED: set("REF_APPLYING", "INDETERMINATE"),
  REF_APPLYING: set("REF_OBSERVED", "INDETERMINATE"),
  REF_OBSERVED: set("COMMITTED", "STALE_BASE", "INDETERMINATE"),
  COMMITTED: set("REPORT_PENDING", "ROLLBACK_REQUESTED"),
  REPORT_PENDING: set("REPORTED", "ROLLBACK_REQUESTED"),
  REPORTED: set("ROLLBACK_REQUESTED"),
  REJECTED: set(),
  STALE_BASE: set("PREPARING"),
  INDETERMINATE: set(),
  ROLLBACK_REQUESTED: set("AWAITING_ROLLBACK_AUTHORIZATION", "INDETERMINATE"),
  AWAITING_ROLLBACK_AUTHORIZATION: set("ROLLBACK_PLANNED", "INDETERMINATE"),
  ROLLBACK_PLANNED: set("ROLLBACK_APPLYING", "INDETERMINATE"),
  ROLLBACK_APPLYING: set("ROLLBACK_OBSERVED", "INDETERMINATE"),
  ROLLBACK_OBSERVED: set("ROLLED_BACK", "INDETERMINATE"),
  ROLLED_BACK: set("AWAITING_AUTHORIZATION"),
};

export const AUTHORIZATION_TRANSITIONS: TransitionTable<AuthorizationState> = {
  CHALLENGE_ISSUED: set("SIGNED", "EXPIRED", "REVOKED"),
  SIGNED: set("STORED", "EXPIRED", "REVOKED"),
  STORED: set("CONSUMED", "EXPIRED", "REVOKED"),
  CONSUMED: set(),
  EXPIRED: set(),
  REVOKED: set(),
};

export const REPORT_TRANSITIONS: TransitionTable<ReportState> = {
  PLANNED: set("WRITING", "PUBLICATION_FAILED", "INDETERMINATE"),
  WRITING: set("FILES_OBSERVED", "PUBLICATION_FAILED", "INDETERMINATE"),
  FILES_OBSERVED: set("PUBLISHED", "INDETERMINATE"),
  PUBLISHED: set(),
  PUBLICATION_FAILED: set("PLANNED"),
  INDETERMINATE: set(),
};

export const CLEANUP_TRANSITIONS: TransitionTable<CleanupState> = {
  REQUESTED: set("PLANNED"),
  PLANNED: set("EXECUTING", "CLEANUP_PENDING", "INDETERMINATE"),
  EXECUTING: set("OBSERVING", "CLEANUP_PENDING", "INDETERMINATE"),
  OBSERVING: set("COMPLETED", "CLEANUP_PENDING", "INDETERMINATE"),
  COMPLETED: set(),
  CLEANUP_PENDING: set("PLANNED", "INDETERMINATE"),
  INDETERMINATE: set(),
};

export function canTransition<S extends string>(table: TransitionTable<S>, from: S, to: S): boolean {
  return table[from].has(to);
}

export function assertTransition<S extends string>(table: TransitionTable<S>, from: S, to: S, machine: string): void {
  if (!canTransition(table, from, to)) {
    throw new ArborError("ILLEGAL_TRANSITION", `Illegal ${machine} transition ${from} -> ${to}`, { machine, from, to });
  }
}
