'use strict';
(() => {
  const $=id=>document.getElementById(id);
  let projection=null,stream=null,selection=0,detailSelection=0;
  const text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value&&typeof value==='object'?JSON.stringify(value,null,2):String(value??'unavailable');return e;};
  const json=v=>JSON.stringify(v,null,2);
  const query=(route,values)=>route+'?'+new URLSearchParams(values);
  async function read(url){const r=await fetch(url);const value=await r.json();if(!r.ok)throw new Error(value.error??r.statusText);return value;}
  function show(id){for(const name of ['tree','evidence','diff','logs','replay'])$(name).hidden=name!==id;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===id)));}
  function error(e){$('status').textContent='Read unavailable: '+e.message;}
  function render(p){
    if(!projection||projection.run.id!==p.run.id||projection.run.revision!==p.run.revision){detailSelection++;$('patch').textContent='Select a candidate at the current revision.';$('diff-binding').textContent='';$('events').replaceChildren();$('replay-status').textContent='Select Replay for the current saved revision.';}
    projection=p;const r=p.run,c=r.spec.config;
    $('status').textContent=`Revision ${r.revision} · ${r.state} · ${r.execution}`;
    $('overview').replaceChildren();
    for(const [label,value] of Object.entries({'Material':r.spec.source.root,'Material identity':r.spec.source.materialId,'Objective':`${c.objective.description} · ${c.objective.direction} · ${c.objective.unit}`,'Captured baseline':r.material?.capture.baseline,'Owned incumbent':r.material?.incumbent,'Coordinator / executor':`${r.spec.roles.coordinator.model} / ${r.spec.roles.executor.model}`,'Evaluator / checks':`${c.evaluator.kind} · ${c.evaluator.definition} · ${json(r.spec.evaluation?.command?.checks??c.objective.qualityVetoes)}`,'Budgets':json({limits:c.limits,enforcement:r.spec.enforcement}),'Preset':r.spec.presetSource?.id??'none','Stop / execution reason':r.execution,'Failure':r.error??'none recorded'}))$('overview').append(text('dt',label),text('dd',value));
    $('pending').textContent=r.pendingDecisionId?`Pending review: ${r.pendingDecisionId}. Awaiting the owning Pi. This browser cannot answer.`:'No pending research review. Keeping owned material never applies it to the source.';
    $('uncertainty').textContent=(typeof p.validation==='string'?p.validation:json(p.validation))+' · Descriptive comparisons only. A queued receipt is not completion; native completion is not a measured win.';
    $('nodes').replaceChildren();
    for(const n of p.nodes){const card=text('article','');card.className='node';card.style.marginLeft=Math.min(n.depth??0,10)*16+'px';card.append(text('h3',`${n.type}: ${n.title}`),text('p',`${n.nodeId} · parent ${n.parentId??'root'} · ${n.pruned?'pruned':'eligible topology'}`),text('p',n.rationale));for(const a of p.attempts.filter(a=>a.nodeId===n.nodeId)){const b=text('button',`Inspect candidate ${a.id} · ${a.state}`);b.onclick=()=>candidate(a.id);card.append(b);}for(const l of p.lessons.filter(l=>l.nodeId===n.nodeId))card.append(text('p',`Lesson: ${l.insight} Limitations: ${l.limitations}`));$('nodes').append(card);}
    if(!p.nodes.length)$('nodes').append(text('p','No hypotheses recorded.'));
    $('evaluations').replaceChildren();for(const e of p.evaluations){const tr=document.createElement('tr');const decisions=p.decisions.filter(d=>d.evidenceIds.includes(e.id));for(const value of [e.id,`${e.attemptId??'baseline'} / ${e.split??'development'}`,`${e.state} / ${e.validity} / quality ${e.quality.passed?'passed':'failed'}`,e.analysis,decisions.length?decisions.map(d=>`${d.decisionId}: ${d.decision} · ${d.status}`).join('\n'):'No measured decision'])tr.append(text('td',value));$('evaluations').append(tr);}
    $('native').replaceChildren();for(const a of p.attempts)$('native').append(text('h3',`Attempt ${a.id}: ${a.state}`),text('pre',`Native ID: ${a.nativeId??'unknown'}\nEvidence: ${a.evidenceId??'none'}\n${a.nativeId?'/fabric log '+a.nativeId:'No known native handle. Do not guess.'}`));for(const e of p.evaluations)for(const i of e.invocations)$('native').append(text('pre',`${e.id} / ${i.id}\n${i.role} · ${i.nativeStatus??'unresolved'} · exit ${i.exitCode??'unknown'}\nNative ID: ${i.nativeId??'unknown'}\nFailure: ${i.error??'none recorded'}\nUsage (observational): ${i.usage??'unavailable'}`));for(const a of p.artifact_refs.filter(a=>a.kind==='native-evidence'))$('native').append(text('pre',`${a.id}\n${a.summary}`));
    $('exports').replaceChildren();for(const a of p.artifact_refs.filter(a=>a.path)){const li=document.createElement('li'),link=text('a',`${a.kind}: ${a.path.split('/').at(-1)}`);link.href=query('/api/artifact',{run:r.id,id:a.id});link.download=a.path.split('/').at(-1);li.append(link);$('exports').append(li);}if(!$('exports').children.length)$('exports').append(text('li','No existing exports. Generate in the owning Pi with /arbor export.'));
  }
  async function candidate(attempt){const p=projection,token=++detailSelection;if(!p)return;show('diff');$('diff-binding').textContent='';$('patch').textContent='Loading exact frozen material…';try{const d=await read(query('/api/diff',{run:p.run.id,attempt,revision:String(p.run.revision)}));if(token!==detailSelection||!projection||projection.run.id!==d.runId||projection.run.revision!==d.revision)return;$('diff-binding').textContent=`${attempt} · revision ${d.revision} · candidate parent ${d.parent} → ${d.selected} · captured baseline ${d.baseline}`;$('patch').textContent=d.patch||'No delta from candidate parent.';}catch(e){if(token===detailSelection)$('patch').textContent=e.message;}}
  async function load(){const token=++selection;stream?.close();projection=null;detailSelection++;for(const id of ['overview','nodes','evaluations','native','exports','events'])$(id).replaceChildren();$('pending').textContent='';$('uncertainty').textContent='';$('patch').textContent='Select a candidate at the current revision.';$('diff-binding').textContent='';$('status').textContent='Loading selected research…';const run=$('run').value;if(!run){$('status').textContent='No saved research. Start in the owning Pi.';return;}try{const p=await read(query('/api/projection',{run}));if(token!==selection)return;render(p);stream=new EventSource(query('/api/events',{run}));stream.addEventListener('projection',e=>{if(token===selection)render(JSON.parse(e.data));});stream.addEventListener('error',()=>{if(token!==selection)return;$('status').textContent='Disconnected. Displayed projection is stale. Refresh explicitly.';stream.close();});stream.addEventListener('unavailable',()=>{if(token!==selection)return;$('status').textContent='Live projection unavailable. Refresh explicitly.';stream.close();});}catch(e){if(token===selection)error(e);}}
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=async()=>{show(b.dataset.view);if(b.dataset.view==='replay'&&projection){const selected=projection.run,token=selection;try{const p=await read(query('/api/replay',{run:selected.id}));if(token!==selection||!projection||projection.run.id!==selected.id||projection.run.revision!==p.revision)return;$('replay-status').textContent=`Saved research events through revision ${p.revision}. Not historical workspace reconstruction.`;$('events').replaceChildren(...p.events.map(e=>text('li',json(e))));}catch(e){if(token===selection&&projection?.run.id===selected.id&&projection.run.revision===selected.revision)error(e);}}});
  $('refresh').onclick=load;$('run').onchange=load;
  read('/api/runs').then(runs=>{$('run').replaceChildren(...runs.map(r=>{const o=text('option',`${r.id} · ${r.state} · ${r.objective}`);o.value=r.id;return o;}));const requested=new URLSearchParams(location.search).get('run');if(requested){if(!runs.some(r=>r.id===requested)){const o=text('option',requested+' · explicitly requested');o.value=requested;$('run').append(o);}$('run').value=requested;}return load();}).catch(error);
  window.addEventListener('pagehide',()=>stream?.close());
})();
