import assert from 'node:assert/strict';
import {readFile,writeFile,appendFile,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import test from 'node:test';
import {host} from '../fixtures/pr6-host.js';
import {sourceProvider} from '../fixtures/pr10-sources.js';
import {commandProgram,researchCommand} from '../../src/research/commands.js';
import {BindingStore} from '../../src/managed/BindingStore.js';
const begin=(id:string,overrides:Record<string,unknown>={})=>commandProgram(researchCommand('start',JSON.stringify({runId:id,overrides})));
for(const installed of [false,true])test(`PR10 ${installed?'clean-installed':'source'} public search/fetch, native visited literature, grounded proposals and frozen resume`,{timeout:600000},async t=>{
 const prepare=async(root:string,catalog?:unknown)=>{const app=installed?join(root,'node_modules/pi-fabric-arbor'):process.cwd();await writeFile(join(root,'profile/extensions/sources.ts'),sourceProvider(app,join(root,'trace.jsonl')));if(catalog)await writeFile(join(root,'profile/arbor.sources.json'),JSON.stringify(catalog));await writeFile(join(root,'source/skills/fabric-arbor/roles/literature.md'),'CANDIDATE_LITERATURE_OVERRIDE');const configPath=join(root,'source/arbor.config.json'),config=JSON.parse(await readFile(configPath,'utf8'));config.material.selectedUntracked.push('skills/fabric-arbor/roles/literature.md');await writeFile(configPath,JSON.stringify(config));};
 // Discover real committed public hashes in a native Pi host. No fixture bind,
 // owner middleware, private runtime or replacement research driver.
 const discovery=await host('command',{installed,prepare:r=>prepare(r),program:`const c=await tools.catalog({provider:'pr10public'});const required=await(async()=>{${begin('required',{grounding:{mode:'required',catalog:'public'},search:{maxActorTurns:2}})}})();const local=await(async()=>{${begin('local',{search:{maxActorTurns:2}})}})();const optional=await(async()=>{${begin('optional',{grounding:{mode:'optional',catalog:'public'},search:{maxActorTurns:2}})}})();return JSON.stringify({catalog:c.providers[0].actions,required:compactProjection(required),local:compactProjection(local),optional:compactProjection(optional)});`});t.after(()=>discovery.store.close());
 assert.equal(discovery.value.required.run.execution,'research-stop:grounding');assert.equal(discovery.value.required.evaluations.length,0);assert.equal(discovery.value.local.evaluations.length,1);assert.equal(discovery.value.optional.evaluations.length,1);assert.equal(discovery.value.optional.run.grounding.status,'unavailable');assert.equal(discovery.events.filter(e=>e.event==='pr10.public').length,0);
 const catalog=[{id:'public',search:{ref:'pr10public.search',descriptorHash:discovery.value.catalog.find((a:any)=>a.ref==='pr10public.search').descriptorHash},fetch:{ref:'pr10public.fetch',descriptorHash:discovery.value.catalog.find((a:any)=>a.ref==='pr10public.fetch').descriptorHash}}];
 const provider=(await readFile('tests/fixtures/pr2-fake-provider.ts','utf8')).replace("trace('research.proposal',{kind:p.kind,payload:p.payload,revision:p.revision,incumbent:data.currentIncumbent});",`if(p.kind==='propose'&&p.payload.type==='hypothesis'&&data.sources?.length)p.payload.groundingRefs=[data.sources[0].reference];trace('pr10.grounded',{kind:p.kind,sources:data.sources,refs:p.payload.groundingRefs??[]});trace('research.proposal',{kind:p.kind,payload:p.payload,revision:p.revision,incumbent:data.currentIncumbent});`);
 const program=`let p=await(async()=>{${begin('research',{grounding:{mode:'required',catalog:'public',query:'parser cache',maxSources:1}})}})();const r=p.run;const exported=await tools.call({ref:'arbor.export',args:{runId:r.id,materialId:r.spec.source.materialId,epoch:r.epoch,revision:r.revision,commandId:'grounding-export',format:'json'}});const minimized=await(async()=>{${begin('minimized',{objective:{direction:'minimize'},grounding:{mode:'required',catalog:'public',query:'parser cache',maxSources:1},search:{maxActorTurns:2}})}})();await components.reload({id:'arbor'});const before=await tools.call({ref:'arbor.inspect',args:{runId:r.id}});const b=before.run;const resumed=await tools.call({ref:'arbor.runResearch',args:{runId:b.id,materialId:b.spec.source.materialId,epoch:b.epoch,revision:b.revision,commandId:'grounding-resume',resume:true}});const small=p=>({run:{grounding:p.run.grounding,execution:p.run.execution,error:p.run.error,spec:{roleBundle:p.run.spec.roleBundle,config:{objective:p.run.spec.config.objective}}}});return JSON.stringify({p:small(p),resumed:small(resumed),minimized:small(minimized),exported});`;
 const h=await host('command',{installed,prepare:r=>prepare(r,catalog),providerSource:provider,program});t.after(()=>h.store.close());
 assert.deepEqual(h.value.resumed.run.grounding,h.value.p.run.grounding);assert.equal(h.value.resumed.run.spec.roleBundle.id,h.value.p.run.spec.roleBundle.id);assert.equal(h.value.p.run.grounding.status,'complete',h.root+': '+h.value.p.run.error);assert.equal(h.value.p.run.execution,'research-stop:attempt-budget',h.root);assert.equal(h.events.filter(e=>e.event==='pr10.public').length,4);assert.equal(h.value.minimized.run.grounding.status,'complete');assert.equal(h.value.minimized.run.spec.config.objective.direction,'minimize');
 const native=h.events.filter(e=>e.event==='pr10.literature');assert.ok(native.length>=2);assert.ok(native.every(e=>e.data.bootstrap&&e.data.evidence&&!e.data.collision&&e.data.tools.length===1&&e.data.tools[0]==='read'));assert.ok(native.some(e=>e.data.reads===1&&JSON.stringify(e.data.readContent).includes('Caching avoids repeated parsing.')));
 const exported=JSON.parse(await readFile(h.value.exported.value.path,'utf8')),inspections=exported.artifact_refs.filter((a:any)=>a.kind==='source-inspection');assert.ok(exported.run.material.capture.files.includes('skills/fabric-arbor/roles/literature.md'));assert.equal(inspections.length,1);const inspection=inspections[0];assert.equal(inspection.passage,'Caching avoids repeated parsing.');assert.ok(!JSON.stringify(inspections).includes('DISCOVERY_ONLY_NOT_INSPECTED'));assert.ok(exported.nodes.filter((n:any)=>n.type==='hypothesis').every((n:any)=>n.groundingRefs[0].sourceId===inspection.id));assert.ok(exported.lessons.every((l:any)=>l.provenance.sourceIds.includes(inspection.id)));assert.ok(exported.trajectories.every((tr:any)=>tr.context.sourceIds.includes(inspection.id)));
 const bindings=new BindingStore(join(h.root,'state/execution-bindings.sqlite3'));try{const b=bindings.forMaterial(exported.run.spec.source.materialId,exported.run.spec.identity).find(b=>b.literature);assert.ok(b);assert.equal(b.state,'completed');assert.equal(b.literatureResult!.nativeId,inspection.nativeId);assert.equal(b.literatureResult!.requestId,inspection.requestId);assert.ok(b.roleInvocations!.some(i=>i.role==='literature'&&i.tools.join(',')==='read'&&i.phases.join(',')==='evidence'&&i.model==='arbor-pr2-fake/deterministic'));}finally{bindings.close();}
 await mkdir('.runtime/pr10-gates',{recursive:true});await appendFile('.runtime/pr10-gates/native-grounding.jsonl',JSON.stringify({installed,discovery:discovery.root,root:h.root,nativeReads:native.length,sourceId:inspection.id,nativeId:inspection.nativeId,export:h.value.exported.value.path})+'\n');
});
