import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {ResearchStore} from '../../src/research/ResearchStore.js';
import {readFile,writeFile,appendFile,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import test from 'node:test';
import {host} from '../fixtures/pr6-host.js';
import {sourceProvider} from '../fixtures/pr10-sources.js';
import {commandProgram,researchCommand} from '../../src/research/commands.js';
import {BindingStore} from '../../src/managed/BindingStore.js';
const begin=(id:string,overrides:Record<string,unknown>={})=>commandProgram(researchCommand('start',JSON.stringify({runId:id,overrides})));
for(const installed of [false,true])test(`PR10 ${installed?'clean-installed':'source'} public search/fetch, native visited literature, grounded proposals and frozen resume`,{timeout:600000},async t=>{
 const prepare=async(root:string,catalog?:unknown)=>{const app=installed?join(root,'node_modules/pi-fabric-arbor'):process.cwd();await writeFile(join(root,'profile/extensions/sources.ts'),sourceProvider(app,join(root,'trace.jsonl')));if(catalog)await writeFile(join(root,'profile/arbor.sources.json'),JSON.stringify(catalog));await writeFile(join(root,'source/skills/fabric-arbor/roles/literature.md'),'CANDIDATE_LITERATURE_OVERRIDE');const configPath=join(root,'source/arbor.config.json'),config=JSON.parse(await readFile(configPath,'utf8'));config.material.selectedUntracked.push('skills/fabric-arbor/roles/literature.md');await writeFile(configPath,JSON.stringify(config));};
 // Discover real committed public hashes in a native Pi host. No fixture bind,
 // owner middleware, private runtime or replacement research driver.
 const discovery=await host('command',{installed,prepare:r=>prepare(r),program:`const c=await tools.catalog({provider:'pr10public'});const required=await(async()=>{${begin('required',{grounding:{mode:'required',catalog:'public'},search:{maxActorTurns:2}})}})();const local=await(async()=>{${begin('local',{search:{maxActorTurns:2}})}})();const optional=await(async()=>{${begin('optional',{grounding:{mode:'optional',catalog:'public'},search:{maxActorTurns:2}})}})();return JSON.stringify({catalog:c.providers[0].actions,required:compactProjection(required),local:compactProjection(local),optional:compactProjection(optional)});`});t.after(()=>discovery.store.close());
 assert.equal(discovery.value.required.run.execution,'research-stop:grounding');assert.equal(discovery.value.required.evaluations.length,0);assert.equal(discovery.value.local.evaluations.length,1);assert.equal(discovery.value.optional.evaluations.length,1);assert.equal(discovery.value.optional.run.grounding.status,'unavailable');assert.equal(discovery.events.filter(e=>e.event==='pr10.public').length,0);
 const catalog=[{id:'public',search:{ref:'pr10public.search',descriptorHash:discovery.value.catalog.find((a:any)=>a.ref==='pr10public.search').descriptorHash},fetch:{ref:'pr10public.fetch',descriptorHash:discovery.value.catalog.find((a:any)=>a.ref==='pr10public.fetch').descriptorHash}}];
 // A real SQLite ingestion failure after native completion, removed only by the
 // external test driver. Native results and admission always come from production.
 let crashBefore:any,crashNative:any;
 const crash=await host('command',{installed,prepare:async root=>{await prepare(root,catalog);const app=installed?join(root,'node_modules/pi-fabric-arbor'):process.cwd();const sources=sourceProvider(app,join(root,'trace.jsonl')).replace("import {appendFileSync}","import {DatabaseSync} from 'node:sqlite';\nimport {appendFileSync}").replace("if(name==='fetch')return",`if(name==='fetch'){const db=new DatabaseSync(${JSON.stringify(join(root,'state/research.sqlite3'))});db.exec("CREATE TRIGGER pr10_ingestion_fault BEFORE INSERT ON artifact_refs WHEN json_extract(NEW.value,'$.kind')='source-inspection' BEGIN SELECT RAISE(ABORT,'PR10 crash before inspection commit'); END");db.close();}if(name==='fetch')return`);await writeFile(join(root,'profile/extensions/sources.ts'),sources);},rpcJourney:async(client,root)=>{
  await client.command('ARBOR_COMMAND_PROGRAM='+JSON.stringify(`const p=await(async()=>{${begin('crash',{grounding:{mode:'required',catalog:'public',query:'parser cache',maxSources:1},search:{maxActorTurns:1}})}})();return JSON.stringify({p});`));
  const research=new ResearchStore(join(root,'state/research.sqlite3'));try{crashBefore=research.projection('crash');}finally{research.close();}
  assert.equal(crashBefore.run.grounding.status,'blocked');assert.match(crashBefore.run.error,/PR10 crash before inspection commit/);assert.equal(crashBefore.evaluations.length,0);
  const bindings=new BindingStore(join(root,'state/execution-bindings.sqlite3'));try{const b=bindings.forMaterial(crashBefore.run.spec.source.materialId,crashBefore.run.spec.identity).find(b=>b.literature)!;assert.equal(b.state,'completed');crashNative=b.literatureResult;assert.ok(crashNative);}finally{bindings.close();}
  const db=new DatabaseSync(join(root,'state/research.sqlite3'));try{db.exec('DROP TRIGGER pr10_ingestion_fault');}finally{db.close();}
  await client.command('ARBOR_COMMAND_PROGRAM='+JSON.stringify("await components.reload({id:'arbor'});return JSON.stringify({reloaded:true});"));
  const journal=new DatabaseSync(join(root,'state/execution-bindings.sqlite3'));
  try{
   const original=journal.prepare("SELECT * FROM execution_bindings WHERE json_extract(value,'$.literature.runId')='crash'").get()!;
   const effects=async()=>{const events=(await readFile(join(root,'trace.jsonl'),'utf8')).trim().split('\n').map(l=>JSON.parse(l));return {sources:events.filter(e=>e.event==='pr10.public').length,spawns:events.filter(e=>e.event==='native.result'&&e.data.ref==='agents.spawn').length};};
   const beforeEffects=await effects();assert.equal(beforeEffects.spawns,1);
   for(const fault of ['missing-binding','missing-handle','unresolved','task','request','epoch','model','owner','bundle','result']){
    const value=JSON.parse(String(original.value));
    if(fault==='missing-binding')journal.prepare('DELETE FROM execution_bindings WHERE id=?').run(original.id!);
    else{if(fault==='missing-handle')delete value.dispatches[0].nativeId;if(fault==='unresolved')value.state='interrupted';if(fault==='task')value.workers[0].task+=' forged';if(fault==='request')value.literature.request.cwd+='/forged';if(fault==='epoch')value.literature.epoch='forged';if(fault==='model')value.spec.model='fake/other';if(fault==='owner')value.owner.ownerIdentityId='forged';if(fault==='bundle')value.roleInvocations[0].bundleId='forged';if(fault==='result')value.literatureResult.value.sources[0].claim='forged';journal.prepare('UPDATE execution_bindings SET value=? WHERE id=?').run(JSON.stringify(value),original.id!);}
    try{
     await client.command('ARBOR_COMMAND_PROGRAM='+JSON.stringify(`await components.reload({id:'arbor'});const refused=await(async()=>{${commandProgram(researchCommand('resume','crash'))}})();return JSON.stringify({refused});`));
     const reader=new ResearchStore(join(root,'state/research.sqlite3'));try{const p:any=reader.projection('crash')!;assert.equal(p.run.grounding!.status,'blocked',fault);assert.equal(p.evaluations.length,0,fault);assert.equal(p.artifact_refs.some((a:any)=>a.kind==='source-inspection'),false,fault);}finally{reader.close();}
     assert.deepEqual(await effects(),beforeEffects,fault+': replay added a source or native effect');
    }finally{journal.prepare('INSERT OR REPLACE INTO execution_bindings (id,generation,revision,value) VALUES (?,?,?,?)').run(original.id!,original.generation!,original.revision!,original.value!);}
   }
  }finally{journal.close();}
  await client.command('ARBOR_COMMAND_PROGRAM='+JSON.stringify(`await components.reload({id:'arbor'});const resumed=await(async()=>{${commandProgram(researchCommand('resume','crash'))}})();return JSON.stringify({resumed});`));
 }});t.after(()=>crash.store.close());
 assert.equal(crash.value.resumed.run.grounding.status,'complete',crash.root+': '+crash.value.resumed.run.error);assert.notEqual(crash.value.resumed.run.generation,crashBefore.run.generation);assert.equal(crash.events.filter(e=>e.event==='pr10.public').length,2,'Replay must add zero search/fetch');
 const crashSources=crash.value.resumed.artifact_refs.filter((a:any)=>a.kind==='source-inspection');assert.equal(crashSources.length,1);assert.equal(crashSources[0].nativeId,crashNative.nativeId);assert.equal(crashSources[0].requestId,crashNative.requestId);assert.equal(crashSources[0].generation,crashBefore.run.generation);assert.equal(crashSources[0].specId,crashBefore.run.spec.identity);assert.equal(crashSources[0].epoch,crashBefore.run.epoch);assert.equal(crashSources[0].roleBundleId,crashNative.roleBundleId);assert.equal(crashSources[0].model,crashNative.model);assert.deepEqual({accessId:crashSources[0].accessId,passage:crashSources[0].passage,claim:crashSources[0].claim,limitations:crashSources[0].limitations},crashNative.value.sources[0]);
 const crashBindings=new BindingStore(join(crash.root,'state/execution-bindings.sqlite3'));try{const bindings=crashBindings.forMaterial(crashBefore.run.spec.source.materialId,crashBefore.run.spec.identity).filter(b=>b.literature);assert.equal(bindings.length,1);assert.equal(bindings[0]!.dispatches.length,1,'Replay must add zero literature spawn');assert.deepEqual(bindings[0]!.literatureResult,crashNative);}finally{crashBindings.close();}
 await mkdir('.runtime/pr10-delayed',{recursive:true});await appendFile('.runtime/pr10-delayed/native-crash.jsonl',JSON.stringify({installed,root:crash.root,nativeId:crashNative.nativeId,requestId:crashNative.requestId,sourceId:crashSources[0].id,additionalSpawn:0,additionalSearch:0,additionalFetch:0})+'\n');
 const provider=(await readFile('tests/fixtures/pr2-fake-provider.ts','utf8')).replace("trace('research.proposal',{kind:p.kind,payload:p.payload,revision:p.revision,incumbent:data.currentIncumbent});",`if(p.kind==='propose'&&p.payload.type==='hypothesis'&&data.sources?.length)p.payload.groundingRefs=[data.sources[0].reference];trace('pr10.grounded',{kind:p.kind,sources:data.sources,refs:p.payload.groundingRefs??[]});trace('research.proposal',{kind:p.kind,payload:p.payload,revision:p.revision,incumbent:data.currentIncumbent});`);
 const program=`let p=await(async()=>{${begin('research',{grounding:{mode:'required',catalog:'public',query:'parser cache',maxSources:1}})}})();const r=p.run;const exported=await tools.call({ref:'arbor.export',args:{runId:r.id,materialId:r.spec.source.materialId,epoch:r.epoch,revision:r.revision,commandId:'grounding-export',format:'json'}});const minimized=await(async()=>{${begin('minimized',{objective:{direction:'minimize'},grounding:{mode:'required',catalog:'public',query:'parser cache',maxSources:1},search:{maxActorTurns:2}})}})();await components.reload({id:'arbor'});const before=await tools.call({ref:'arbor.inspect',args:{runId:r.id}});const b=before.run;const resumed=await(async()=>{${commandProgram(researchCommand('resume','research'))}})();const small=p=>({run:{grounding:p.run.grounding,execution:p.run.execution,error:p.run.error,spec:{roleBundle:p.run.spec.roleBundle,config:{objective:p.run.spec.config.objective}}}});return JSON.stringify({p:small(p),resumed:small(resumed),minimized:small(minimized),exported});`;
 const h=await host('command',{installed,prepare:r=>prepare(r,catalog),providerSource:provider,program});t.after(()=>h.store.close());
 assert.deepEqual(h.value.resumed.run.grounding,h.value.p.run.grounding);assert.equal(h.value.resumed.run.spec.roleBundle.id,h.value.p.run.spec.roleBundle.id);assert.equal(h.value.p.run.grounding.status,'complete',h.root+': '+h.value.p.run.error);assert.equal(h.value.p.run.execution,'research-stop:attempt-budget',h.root);assert.equal(h.events.filter(e=>e.event==='pr10.public').length,4);assert.equal(h.value.minimized.run.grounding.status,'complete');assert.equal(h.value.minimized.run.spec.config.objective.direction,'minimize');
 const native=h.events.filter(e=>e.event==='pr10.literature');assert.ok(native.length>=2);assert.ok(native.every(e=>e.data.bootstrap&&e.data.evidence&&!e.data.collision&&e.data.tools.length===1&&e.data.tools[0]==='read'));assert.ok(native.some(e=>e.data.reads===1&&JSON.stringify(e.data.readContent).includes('Caching avoids repeated parsing.')));
 const exported=JSON.parse(await readFile(h.value.exported.value.path,'utf8')),inspections=exported.artifact_refs.filter((a:any)=>a.kind==='source-inspection');assert.ok(exported.run.material.capture.files.includes('skills/fabric-arbor/roles/literature.md'));assert.equal(inspections.length,1);const inspection=inspections[0];assert.equal(inspection.passage,'Caching avoids repeated parsing.');assert.ok(!JSON.stringify(inspections).includes('DISCOVERY_ONLY_NOT_INSPECTED'));assert.ok(exported.nodes.filter((n:any)=>n.type==='hypothesis').every((n:any)=>n.groundingRefs[0].sourceId===inspection.id));assert.ok(exported.lessons.every((l:any)=>l.provenance.sourceIds.includes(inspection.id)));assert.ok(exported.trajectories.every((tr:any)=>tr.context.sourceIds.includes(inspection.id)));
 const bindings=new BindingStore(join(h.root,'state/execution-bindings.sqlite3'));try{const b=bindings.forMaterial(exported.run.spec.source.materialId,exported.run.spec.identity).find(b=>b.literature);assert.ok(b);assert.equal(b.state,'completed');assert.equal(b.literatureResult!.nativeId,inspection.nativeId);assert.equal(b.literatureResult!.requestId,inspection.requestId);assert.ok(b.roleInvocations!.some(i=>i.role==='literature'&&i.tools.join(',')==='read'&&i.phases.join(',')==='evidence'&&i.model==='arbor-pr2-fake/deterministic'));}finally{bindings.close();}
 await mkdir('.runtime/pr10-gates',{recursive:true});await appendFile('.runtime/pr10-gates/native-grounding.jsonl',JSON.stringify({installed,discovery:discovery.root,root:h.root,nativeReads:native.length,sourceId:inspection.id,nativeId:inspection.nativeId,export:h.value.exported.value.path})+'\n');
});
