/// <reference lib="dom" />
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {mkdir,readFile,readdir,lstat,readlink,writeFile,appendFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import test from 'node:test';
import {chromium} from 'playwright';
import {host} from '../fixtures/pr6-host.js';
import {externalFixtureSource} from '../fixtures/pr4-external.js';
import {SourceView} from '../../src/presentation/SourceView.js';
import type {RpcJourney} from '../fixtures/pr12-rpc.js';
const gates=resolve('.runtime/pr12-gates');
async function snapshot(root:string){const entries:Record<string,string>={};async function walk(path:string){for(const name of (await readdir(path)).sort()){const file=join(path,name),s=await lstat(file);if(s.isSymbolicLink())entries[file]='link:'+await readlink(file);else if(s.isDirectory())await walk(file);else if(!file.endsWith('-shm'))entries[file]=`${s.mode}:`+createHash('sha256').update(await readFile(file)).digest('hex');}}await walk(join(root,'state'));await walk(join(root,'source'));return entries;}
const respond=(r:any)=>r.method==='confirm'?{confirmed:true}:r.method==='input'?{value:'PR12 exact bounded research'}:r.options?.includes('maximize')?{value:'maximize'}:{cancelled:true};
// Poll existing persisted facts only. Main never selects or dispatches a research step.
async function researchSettled(view:SourceView,runId:string,after=-1){const deadline=Date.now()+120000;for(;;){const p=view.project(runId)!;if(p.run.revision>after&&p.run.active===0&&(p.run.execution.startsWith('research-stop:')||p.run.execution==='background-research-interrupted'||['cancelled','cleanup_pending'].includes(p.run.state)))return p;if(Date.now()>deadline)throw new Error('Research did not settle: '+JSON.stringify({root:view.directory,run:p.run.state,execution:p.run.execution,error:p.run.error}));await new Promise(r=>setTimeout(r,20));}}
async function inspect(client:RpcJourney,runId:string){await client.command('ARBOR_COMMAND_PROGRAM='+JSON.stringify(`return JSON.stringify({p:await tools.call({ref:'arbor.inspect',args:{runId:${JSON.stringify(runId)}}})});`));}
async function browserProbe(client:RpcJourney,root:string,app:string,runId:string,label:string){
 const notices=await client.command('/arbor browser',undefined,false),notice=notices.find(r=>r.method==='notify'&&r.message.includes('read-only browser:'));assert.ok(notice,root);const url=notice.message.split('browser: ')[1];
 const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1280,height:960}}),errors:string[]=[],requests:string[]=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push(r.method()));
 const source=new SourceView(join(root,'state')),p=source.project(runId)!;const before=await snapshot(root);
 const missing=await browser.newPage();await missing.goto(new URL('/?run=missing-explicit-run',url).href);await missing.waitForFunction(()=>document.getElementById('status')!.textContent!.startsWith('Read unavailable:'));assert.equal(await missing.getByLabel('Research run').inputValue(),'missing-explicit-run');assert.equal(await missing.locator('#nodes article').count(),0);await missing.close();
 await page.goto(url);await page.waitForFunction(revision=>document.getElementById('status')?.textContent?.startsWith('Revision '+revision),p.run.revision);
 assert.equal(await page.getByRole('heading',{name:'Research evidence',exact:true}).isVisible(),true);assert.equal(await page.getByLabel('Research run').inputValue(),runId);
 assert.match(await page.locator('#pending').innerText(),p.run.pendingDecisionId?/Pending review.*owning Pi/:/No pending/);
 assert.match(await page.locator('#overview').innerText(),new RegExp(p.run.material.capture.baseline));assert.match(await page.locator('#overview').innerText(),new RegExp(p.run.material.incumbent));
 const screenshots:string[]=[];async function proof(name:string){const path=join(root,`pr12-${name}.png`);try{await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await page.screenshot({path,fullPage:true});}catch(error){throw new Error(`Screenshot ${name} at ${root}: ${String(error)}`);}screenshots.push(path);}
 await proof('tree');
 for(const name of ['Evidence','Logs','Replay']){await page.getByRole('button',{name,exact:true}).click();await page.getByRole('heading',{name:name==='Evidence'?'Exact evaluation evidence':name==='Logs'?'Native references and failures':'Saved event replay',exact:true}).waitFor({state:'visible'});if(name==='Replay')await page.waitForFunction(()=>document.getElementById('events')!.children.length>0);await proof(name.toLowerCase());}
 assert.equal(await page.locator('form,input,textarea').count(),0);assert.equal(await page.getByRole('button',{name:/approve|reject|start|pause|resume|cancel|apply|export|keep|discard/i}).count(),0);
 if(p.attempts.length){await page.getByRole('button',{name:'Tree',exact:true}).click();await page.getByRole('button',{name:new RegExp('Inspect candidate '+p.attempts[0].id+' ')}).click();await page.waitForFunction(()=>document.getElementById('patch')!.textContent!.includes('diff --git'));await proof('diff');assert.equal(await page.locator('#patch').innerText(),source.diff(runId,p.attempts[0].id,p.run.revision).patch);}
 // F3: every candidate patch uses its recorded parent, not accumulated incumbent history.
 for(const c of p.run.material.candidates.filter((c:any)=>c.oid)){assert.equal(source.diff(runId,c.id,p.run.revision).patch,execFileSync('git',['diff','--no-ext-diff','--no-textconv','--binary',c.parent,c.oid,'--'],{cwd:p.run.material.capture.repository,encoding:'utf8'}));}
 if(p.attempts.length>1){
  const first=p.attempts[0].id,second=p.attempts[1].id;let release!:()=>void,entered!:()=>void,held=false;const ready=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);
  await page.route('**/api/diff?*',async route=>{if(!held&&new URL(route.request().url()).searchParams.get('attempt')===first){held=true;entered();await gate;}await route.continue();});
  try{await page.getByRole('button',{name:'Tree',exact:true}).click();await page.getByRole('button',{name:new RegExp('Inspect candidate '+first+' ')}).click();await ready;await page.getByRole('button',{name:'Tree',exact:true}).click();await page.getByRole('button',{name:new RegExp('Inspect candidate '+second+' ')}).click();await page.waitForFunction(id=>document.getElementById('diff-binding')!.textContent!.startsWith(id+' ·'),second);
   const late=page.waitForResponse(r=>r.url().includes('/api/diff?')&&new URL(r.url()).searchParams.get('attempt')===first);release();await (await late).finished();await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>r())));assert.ok((await page.locator('#diff-binding').innerText()).startsWith(second+' ·'),'Late first candidate overwrote latest selection');await proof('diff-parent');
  }finally{release();await page.unroute('**/api/diff?*');}
 }
 const base=new URL(url).origin,cli=join(app,'bin/pi-fabric-arbor.mjs');const cliRead=(args:string[])=>execFileSync(process.execPath,[cli,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']});
 const api=await (await fetch(base+'/api/projection?run='+runId)).json();assert.deepEqual(api,p);assert.deepEqual(JSON.parse(cliRead(['inspect','--state',join(root,'state'),'--run',runId])),p);
 assert.deepEqual(JSON.parse(cliRead(['replay','--state',join(root,'state'),'--run',runId])),await (await fetch(base+'/api/replay?run='+runId)).json());
 for(const a of p.artifact_refs.filter((a:any)=>a.path)){const bytes=await source.artifact(runId,a.id);assert.deepEqual(Buffer.from(await (await fetch(base+'/api/artifact?'+new URLSearchParams({run:runId,id:a.id}))).arrayBuffer()),bytes);assert.equal(cliRead(['artifact','--state',join(root,'state'),'--run',runId,'--id',a.id]),bytes.toString());}
 for(const verb of ['setup','scaffold','start','resume','pause','cancel','steer','review','keep','discard','apply','undo-apply','export','validate','continue-partial','restart-parent','revise-roles']){assert.throws(()=>cliRead([verb,'--state',join(root,'state'),'--run',runId]),(e:any)=>e.status===2);for(const method of ['GET','POST','PUT','PATCH','DELETE'])assert.ok([404,405].includes((await fetch(base+'/api/'+verb,{method})).status));}
 for(const route of ['/api/projection?run='+runId+'&action=cancel','/api/artifact?run='+runId+'&id=x&generate=true'])assert.equal((await fetch(base+route)).status,405);
 assert.deepEqual(errors,[]);assert.ok(requests.every(m=>m==='GET'));assert.deepEqual(source.project(runId),p);assert.deepEqual(await snapshot(root),before,'Reads changed research/control/material/export bytes (SQLite shared-memory coordination excluded)');
 // Hold actual old server responses across a real owner-only revision change.
 let release!:()=>void;const held=new Promise<void>(r=>release=r);let replayReady!:()=>void,diffReady!:()=>void;
 const readyReplay=new Promise<void>(r=>replayReady=r),readyDiff=new Promise<void>(r=>diffReady=r);
 await page.route('**/api/replay?*',async route=>{const response=await route.fetch();replayReady();await held;await route.fulfill({response});});
 await page.route('**/api/diff?*',async route=>{const response=await route.fetch();diffReady();await held;await route.fulfill({response});});
 try{
  await page.getByRole('button',{name:'Replay',exact:true}).click();await readyReplay;
  await page.getByRole('button',{name:'Tree',exact:true}).click();await page.getByRole('button',{name:new RegExp('Inspect candidate '+p.attempts[0].id+' ')}).click();await readyDiff;
  const revision=p.run.revision;await client.command('/arbor steer PR12 retained steering');await page.waitForFunction(old=>{const text=document.getElementById('status')?.textContent??'';return text.startsWith('Revision ')&&!text.startsWith('Revision '+old+' ');},revision);assert.ok(source.project(runId)!.run.revision>revision);
  const replies=Promise.all(['/api/replay?','/api/diff?'].map(path=>page.waitForResponse(r=>r.url().includes(path)).then(r=>r.finished())));release();await replies;await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>r())));
  assert.equal(await page.locator('#events').count(),1);assert.equal(await page.locator('#events li').count(),0,'Late replay restored previous revision');assert.equal(await page.locator('#diff-binding').innerText(),'','Late diff restored previous revision');await proof('sse-revision');
 }finally{release();await page.unroute('**/api/replay?*');await page.unroute('**/api/diff?*');}
 // A late failed refresh cannot overwrite the newer successful selection.
 let releaseError!:()=>void,errorReady!:()=>void,once=false;const errorGate=new Promise<void>(r=>releaseError=r),readyError=new Promise<void>(r=>errorReady=r);
 await page.route('**/api/projection?*',async route=>{if(once){await route.continue();return;}once=true;errorReady();await errorGate;await route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'delayed old read failure'})});});
 try{await page.getByRole('button',{name:'Refresh current revision',exact:true}).click();await readyError;await page.getByRole('button',{name:'Refresh current revision',exact:true}).click();const current=source.project(runId)!.run.revision;await page.waitForFunction(r=>document.getElementById('status')!.textContent!.startsWith('Revision '+r+' '),current);const reply=page.waitForResponse(r=>r.url().includes('/api/projection?')&&r.status()===409);releaseError();await (await reply).finished();await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>r())));assert.ok((await page.locator('#status').innerText()).startsWith('Revision '+current+' '));await page.getByRole('button',{name:'Tree',exact:true}).click();await proof('final-tree');}finally{releaseError();await page.unroute('**/api/projection?*');}
 assert.deepEqual(errors,[]);assert.ok(requests.every(m=>m==='GET'));
 await appendFile(join(gates,'browser.jsonl'),JSON.stringify({root,label,revision:p.run.revision,finalRevision:source.project(runId)!.run.revision,pending:p.run.pendingDecisionId,attempts:p.attempts.length,exports:p.artifact_refs.filter((a:any)=>a.path).length,screenshots,errors,requestMethods:[...new Set(requests)],noninterference:true,lateCandidate:true,lateReplay:true,lateRefreshError:true,sse:true})+'\n');
 }finally{await browser.close();}
}
for(const installed of [false,true])test(`PR12 ${installed?'installed':'source'} actual owning Pi intake research presentation exports and controls`,{timeout:390000},async t=>{
 await mkdir(gates,{recursive:true});let runId='';const h=await host('command',{installed,prepare:async root=>writeFile(join(root,'profile/extensions/reload.ts'),await readFile('tests/fixtures/pr1-reload-extension.ts')),rpcJourney:async(client,root)=>{
  const card=await client.command('/arbor',undefined,false);assert.ok(card.some(r=>r.method==='setWidget'&&JSON.stringify(r).includes('launch card')));
  const start=await client.command('/arbor start',respond);assert.ok(start.some(r=>r.method==='confirm'&&r.message.includes('No automatic source apply')));assert.ok(start.some(r=>r.method==='notify'&&r.message.includes('not yet a control receipt')));
  const view=new SourceView(join(root,'state'));runId=view.runs()[0]!.id;const p=await researchSettled(view,runId);assert.equal(p.attempts.length,4,root+': '+p.run.error);assert.ok(p.decisions.some((d:any)=>d.status==='measured-keep'));assert.ok(p.evaluations.some((e:any)=>!e.quality.passed||e.validity==='invalid'));
  const show=await client.command('/arbor show',r=>r.method==='select'?{value:r.options.find((o:string)=>o.startsWith('Candidate '))}:{cancelled:true},false);assert.ok(show.some(r=>r.method==='editor'&&r.prefill.includes('diff --git')));assert.ok(show.some(r=>r.method==='set_editor_text'&&r.text.startsWith('/fabric log ')));
  const beforeNative=(await readFile(join(root,'trace.jsonl'),'utf8')).split('\n').filter(l=>l.includes('"event":"main.inference"')).length;
  await client.command('/arbor show',r=>r.method==='select'?{value:'Native Fabric topology'}:{cancelled:true},false);
  const nativeId=p.attempts.find((a:any)=>a.nativeId).nativeId;await client.command('/fabric log '+nativeId,undefined,false);
  assert.equal((await readFile(join(root,'trace.jsonl'),'utf8')).split('\n').filter(l=>l.includes('"event":"main.inference"')).length,beforeNative,'Native navigation incorrectly triggered Main inference');
  await client.command('/arbor apply',r=>({value:r.options.find((o:string)=>o==='Apply exact source delta')??r.options[0]}));
  assert.equal(await readFile(join(root,'source/program.cjs'),'utf8'),'module.exports={level:4,score:3};\n');
  const applied=view.project(runId)!.artifact_refs.find((a:any)=>a.kind==='source-operation'),originalBytes=await view.artifact(runId,applied.id);
  await client.command('/arbor apply --run '+runId+' '+applied.commandId,r=>({value:r.options.find((o:string)=>o==='Apply exact source delta')??r.options[0]}));
  assert.deepEqual(await view.artifact(runId,applied.id),originalBytes,'Recovery changed a published source-journal artifact');
  for(const format of ['json','report','trajectory'])await client.command('/arbor export '+format);
  const app=installed?join(root,'node_modules/pi-fabric-arbor'):process.cwd();await browserProbe(client,root,app,runId,installed?'installed':'source');
  await client.command('/arbor undo-apply',r=>({value:r.options.find((o:string)=>o==='Undo exact source delta')??r.options[0]}));
  assert.equal(await readFile(join(root,'source/program.cjs'),'utf8'),'module.exports={level:0,score:1};\n');
  await client.command('/arbor lessons exact');await client.command('/arbor pause');
  const old=(await client.command('/arbor browser',undefined,false)).find(r=>r.method==='notify'&&r.message.includes('browser:')).message.split('browser: ')[1];
  const spec=view.project(runId)!.run.spec;await client.command('/pr1-reload',undefined,false);await assert.rejects(fetch(old));const doctor=await client.command('/arbor doctor',undefined,false);assert.ok(doctor.some(r=>r.method==='notify'&&r.message.includes('Bounded owner-led research')));
  const beforeResume=view.project(runId)!.run.revision;await client.command('/arbor resume');await researchSettled(view,runId,beforeResume);assert.deepEqual(view.project(runId)!.run.spec,spec);await client.command('/arbor cancel');assert.equal(view.project(runId)!.run.state,'cancelled');
  await inspect(client,runId);
 }});t.after(()=>h.store.close());const rpc=JSON.parse(await readFile(join(h.root,'pr12-rpc.json'),'utf8'));assert.equal(rpc.failure,undefined,h.root+': '+rpc.failure);assert.equal(h.value.p.run.state,'cancelled');assert.equal(h.value.p.run.id,runId);assert.ok(h.events.some(e=>e.event==='research.proposal'));await appendFile(join(gates,'native.jsonl'),JSON.stringify({root:h.root,installed,runId,revision:h.value.p.run.revision,journeys:[1,2,3,4,5,6,7,8,9]})+'\n');
});
for(const installed of [false,true])for(const hold of ['agents.spawn','agents.ask'])test(`PR12 ${installed?'installed':'source'} normal commands control owner-held ${hold} active work after start acknowledgment`,{timeout:180000},async t=>{
 const providerSource=(await readFile('tests/fixtures/pr2-fake-provider.ts','utf8')).replace('pi.on("tool_result", async event => {','pi.on("tool_result", async (event,ctx) => {').replace('held = true; trace("barrier.held", { ref: proxy.ref });','held = true; trace("barrier.held", { ref: proxy.ref }); ctx.ui.notify("PR12 native work held", "info");').replace('  const fixture: FabricProvider =','  pi.registerCommand("pr12-release", {handler(){ release?.(); }});\n  const fixture: FabricProvider =');
 const h=await host('command',{installed,providerSource,hold,rpcJourney:async(client,root)=>{
  await client.command('/arbor start',respond);
  await client.wait(r=>r.type==='extension_ui_request'&&r.method==='notify'&&r.message==='PR12 native work held');
  const view=new SourceView(join(root,'state')),runId=view.runs()[0]!.id;
  const steering=await client.command('/arbor steer exact active instruction');assert.ok(steering.some(r=>r.type==='agent_settled'));assert.ok(view.project(runId)!.run.steering.includes('exact active instruction'));
  await client.command('ARBOR_COMMAND_PROGRAM='+JSON.stringify(`const p=await tools.call({ref:'arbor.start',args:{runId:'review-run',overrides:{execution:'material'}}});const r=p.run;await tools.call({ref:'arbor.decide',args:{runId:r.id,materialId:r.spec.source.materialId,epoch:r.epoch,revision:r.revision,commandId:'active-review-request',payload:{decisionId:'active-review',nodeId:null,decision:'request_review',evidenceIds:[]}}});return JSON.stringify({p:await tools.call({ref:'arbor.inspect',args:{runId:r.id}})});`));
  assert.equal(view.project('review-run')!.run.pendingDecisionId,'active-review');const reviewed=await client.command('/arbor review --run review-run',r=>({value:r.options?.find((o:string)=>o==='Approve research choice')}));assert.ok(reviewed.some(r=>r.method==='select'&&r.options.includes('Approve research choice')));assert.equal(view.project('review-run')!.decisions.find((d:any)=>d.decisionId==='active-review')?.userReceipt.response,'Approve research choice');assert.equal(view.project('review-run')!.run.pendingDecisionId,null);assert.ok(!(await readFile(join(root,'trace.jsonl'),'utf8')).includes('barrier.released'),'Review was queued behind held work');
  await client.command('/arbor pause --run '+runId);assert.equal(view.project(runId)!.run.state,'paused');
  const cancelling=client.command('/arbor cancel');void cancelling.catch(()=>{});const deadline=Date.now()+15000;while(!view.project(runId)!.controls.some((c:any)=>c.action==='cancel')&&Date.now()<deadline)await new Promise(r=>setTimeout(r,10));assert.equal(view.project(runId)!.controls.find((c:any)=>c.action==='cancel')?.status,'queued','Cancel did not reach active owner');assert.equal(view.project(runId)!.run.state,'interrupted','Unsettled native launch must remain interrupted');assert.ok(!(await readFile(join(root,'trace.jsonl'),'utf8')).includes('"event":"barrier.released"'),'Cancel was merely queued after work');
  await client.command('/pr12-release',undefined,false);await cancelling;assert.equal(view.project(runId)!.run.state,'cancelled');await inspect(client,runId);
 }});t.after(()=>h.store.close());assert.equal(h.value.p.run.state,'cancelled');assert.equal(h.value.p.run.active,0);assert.ok(h.value.p.attempts.length<=1);await appendFile(join(gates,'active-controls.jsonl'),JSON.stringify({root:h.root,installed,hold,reviewed:true,reviewRunId:'review-run',state:h.value.p.run.state,active:h.value.p.run.active,mainAcknowledged:true,controlPolicy:'ordinary-tools'})+'\n');
});
for(const installed of [false,true])test(`PR12 O3 ${installed?'installed':'source'} held ask steering rejects old proposal and asks fresh`,{timeout:180000},async t=>{
 const providerSource=(await readFile('tests/fixtures/pr2-fake-provider.ts','utf8')).replace('pi.on("tool_result", async event => {','pi.on("tool_result", async (event,ctx) => {').replace('held = true; trace("barrier.held", { ref: proxy.ref });','held = true; trace("barrier.held", { ref: proxy.ref }); ctx.ui.notify("PR12 native work held", "info");').replace('  const fixture: FabricProvider =','  pi.registerCommand("pr12-release", {handler(){ release?.(); }});\n  const fixture: FabricProvider =');
 const h=await host('command',{installed,providerSource,hold:'agents.ask',overrides:{limits:{attempts:1,evaluatorCalls:20,activeMs:600000}},rpcJourney:async(client,root)=>{
  await client.command('/arbor start',respond);await client.wait(r=>r.type==='extension_ui_request'&&r.message==='PR12 native work held');const view=new SourceView(join(root,'state')),runId=view.runs()[0]!.id,before=view.project(runId)!;assert.equal(before.attempts.length,0);
  await client.command('/arbor steer fresh held ask instruction');const steered=view.project(runId)!;assert.ok(steered.run.steering.includes('fresh held ask instruction'));assert.ok(steered.run.revision>before.run.revision);assert.ok(!(await readFile(join(root,'trace.jsonl'),'utf8')).includes('barrier.released'));
  await client.command('/pr12-release',undefined,false);const settled=await researchSettled(view,runId);assert.notEqual(settled.run.state,'interrupted',settled.run.error);assert.equal(settled.run.error,null);assert.equal(settled.attempts.length,1);await client.command('/arbor cancel');await inspect(client,runId);
 }});t.after(()=>h.store.close());assert.ok(h.events.filter(e=>e.event==='native.result'&&e.data.ref==='agents.ask').length>=2);await appendFile(join(gates,'held-ask.jsonl'),JSON.stringify({root:h.root,installed,state:h.value.p.run.state,ordinaryTools:true})+'\n');
});
for(const installed of [false,true])for(const hold of ['agents.ask','agents.spawn'])test(`PR12 ${installed?'installed':'source'} actual reload retains held ${hold} settlement`,{timeout:180000},async t=>{
 const providerSource=(await readFile('tests/fixtures/pr2-fake-provider.ts','utf8')).replace('pi.on("tool_result", async event => {','pi.on("tool_result", async (event,ctx) => {').replace('held = true; trace("barrier.held", { ref: proxy.ref });','held = true; trace("barrier.held", { ref: proxy.ref }); ctx.ui.notify("PR12 native work held", "info");').replace('  const fixture: FabricProvider =','  pi.registerCommand("pr12-release", {handler(){ release?.(); }});\n  const fixture: FabricProvider =');
 const h=await host('command',{installed,providerSource,hold,prepare:async root=>writeFile(join(root,'profile/extensions/reload.ts'),await readFile('tests/fixtures/pr1-reload-extension.ts')),rpcJourney:async(client,root)=>{
  await client.command('/arbor start',respond);await client.wait(r=>r.type==='extension_ui_request'&&r.message==='PR12 native work held');const view=new SourceView(join(root,'state')),runId=view.runs()[0]!.id,spec=view.project(runId)!.run.spec,generation=view.project(runId)!.run.generation;
  let reloadDone=false;const reloading=client.command('/pr1-reload',undefined,false).then(()=>{reloadDone=true;});void reloading.catch(()=>{});const deadline=Date.now()+15000;let stopped=false;while(Date.now()<deadline){stopped=(await readFile(join(root,'trace.jsonl'),'utf8')).split('\n').filter(Boolean).map(s=>JSON.parse(s)).some(e=>e.event==='native.result'&&e.data.ref==='agents.stop');if(stopped)break;await new Promise(r=>setTimeout(r,10));}assert.ok(stopped,'Reload did not begin native retirement while ask held');assert.equal(reloadDone,false,'Reload returned before held reply settled');
  await client.command('/pr12-release',undefined,false);await reloading;const p=view.project(runId)!;assert.deepEqual(p.run.spec,spec);assert.equal(p.attempts.length,hold==='agents.ask'?0:1);assert.equal(p.run.active,0);assert.ok(['interrupted','cancelled','paused','cleanup_pending'].includes(p.run.state));assert.equal(p.run.generation,generation);await inspect(client,runId);
 }});t.after(()=>h.store.close());await appendFile(join(gates,'held-reload.jsonl'),JSON.stringify({root:h.root,installed,hold,state:h.value.p.run.state,active:h.value.p.run.active,actualReload:true,heldSettlement:true})+'\n');
});
for(const installed of [false,true])for(const policy of ['deny','ask'])test(`PR12 policy ${installed?'installed':'source'} resume cannot bypass changed agent ${policy} after actual reload`,{timeout:180000},async t=>{
 const h=await host('command',{installed,overrides:{limits:{attempts:1,evaluatorCalls:20,activeMs:600000}},prepare:async root=>writeFile(join(root,'profile/extensions/reload.ts'),await readFile('tests/fixtures/pr1-reload-extension.ts')),rpcJourney:async(client,root)=>{
  await client.command('ARBOR_COMMAND_PROGRAM='+JSON.stringify(`return JSON.stringify({p:await tools.call({ref:'arbor.start',args:{runId:'research'}})});`));await client.command('/arbor pause research');const path=join(root,'source/.pi/fabric.json'),config=JSON.parse(await readFile(path,'utf8'));config.approvals.agent=policy;await writeFile(path,JSON.stringify(config));await client.command('/pr1-reload',undefined,false);
  const result=await client.command('/arbor resume research');const view=new SourceView(join(root,'state'));const last=(await readFile(join(root,'trace.jsonl'),'utf8')).trim().split('\n').map(s=>JSON.parse(s)).filter(e=>e.event==='main.result').at(-1)?.data;if(!(String(last).includes('Runtime error')&&/denied|approval/i.test(String(last))))await researchSettled(view,'research');await client.command('ARBOR_COMMAND_PROGRAM='+JSON.stringify(`const p=await tools.call({ref:'arbor.inspect',args:{runId:'research'}});const r=p.run;let error;try{await tools.call({ref:'arbor.runResearch',args:{runId:r.id,materialId:r.spec.source.materialId,epoch:r.epoch,revision:r.revision,commandId:'direct-bypass',resume:true,background:true}});}catch(e){error=String(e);}return JSON.stringify({p:await tools.call({ref:'arbor.inspect',args:{runId:r.id}}),error});`));const actual=JSON.parse((await readFile(join(root,'trace.jsonl'),'utf8')).trim().split('\n').map(s=>JSON.parse(s)).filter(e=>e.event==='main.result').at(-1).data);assert.match(actual.error,/Fresh agent-risk/);assert.equal(view.project('research')!.attempts.length,0,'Agent-denied resume launched native work through captured component calls');
 }});t.after(()=>h.store.close());const nativeEffects=h.events.filter(e=>e.event==='native.result'&&['agents.create','agents.spawn'].includes(e.data.ref)).length;await appendFile(join(gates,'agent-policy.jsonl'),JSON.stringify({root:h.root,installed,policy,nativeEffects,accepted:false})+'\n');assert.equal(nativeEffects,0,h.root+': agent policy must block native create/spawn');
});
for(const installed of [false,true])for(const deny of ['deny','ask'] as const)test(`PR12 O1 ${installed?'installed':'source'} real provider ${deny} execute admission`,{timeout:180000},async t=>{
 const program=`let p=await tools.call({ref:'arbor.start',args:{runId:'research'}});const r=p.run;const binding={runId:r.id,materialId:r.spec.source.materialId,epoch:r.epoch,revision:r.revision};let error;try{await tools.call({ref:'arbor.evaluate',args:{...binding,commandId:'execute-test',payload:{attemptId:'baseline',evaluationId:'evaluation-initial'}}});}catch(e){error=String(e);}const resumed=await tools.call({ref:'arbor.control',args:{...binding,commandId:'resume-test',action:'resume'}});return JSON.stringify({p:await tools.call({ref:'arbor.inspect',args:{runId:r.id}}),error,resumed});`;
 const h=await host('command',{installed,overrides:{execution:'material'},rpcJourney:async(client,root)=>{await client.command('ARBOR_COMMAND_PROGRAM='+JSON.stringify(`const c=await tools.catalog({provider:'pr4external'});const hash=c.providers[0].actions.find(a=>a.ref==='pr4external.evaluate').descriptorHash;await tools.call({ref:'pr4fixture.bind',args:{hash}});await components.reload({id:'arbor'});return JSON.stringify({registered:true});`));const path=join(root,'source/.pi/fabric.json'),config=JSON.parse(await readFile(path,'utf8'));config.approvals.execute=deny;await writeFile(path,JSON.stringify(config));await client.command('/pr1-reload',undefined,false);await client.command('ARBOR_COMMAND_PROGRAM='+JSON.stringify(program));},prepare:async root=>{const definitionPath=join(root,'definition.json'),definition=JSON.parse(await readFile(definitionPath,'utf8'));definition.kind='provider';definition.command=null;definition.providerAction='pr4external.evaluate';await writeFile(definitionPath,JSON.stringify(definition));const path=join(root,'source/arbor.config.json'),config=JSON.parse(await readFile(path,'utf8'));config.evaluator.kind='provider';await writeFile(path,JSON.stringify(config));const app=JSON.parse(await readFile(join(root,'profile/settings.json'),'utf8')).packages[0];await writeFile(join(root,'profile/extensions/external.ts'),externalFixtureSource(app,join(root,'profile'),root));await writeFile(join(root,'profile/extensions/reload.ts'),await readFile('tests/fixtures/pr1-reload-extension.ts'));}});t.after(()=>h.store.close());assert.match(h.value.error,/denied|approval|requires|permission/i);assert.equal(h.value.resumed.status,'blocked');assert.match(h.value.resumed.reason,/execute-policy/);assert.equal(h.value.p.evaluations.length,0);assert.equal(h.value.p.attempts.length,0);assert.ok(!(await readdir(h.root)).includes('external.jsonl'),'Provider ran despite execute denial');await appendFile(join(gates,'provider-denials.jsonl'),JSON.stringify({root:h.root,installed,deny,evaluations:0,externalCalls:0})+'\n');
});
for(const boundary of ['execute','write'] as const)test(`PR12 actual no-ID commands preserve ${boundary} denial`,{timeout:180000},async t=>{
 const h=await host('command',{...(boundary==='execute'?{deny:'deny' as const}:{writePolicy:'deny' as const}),overrides:{limits:{attempts:1,evaluatorCalls:20,activeMs:600000}},rpcJourney:async(client,root)=>{
  const started=await client.command('/arbor start',respond);const view=new SourceView(join(root,'state')),runId=view.runs()[0]!.id;
  if(boundary==='execute'){assert.match(JSON.stringify(started),/denied|approval|requires|permission/i);assert.equal(view.project(runId)!.evaluations.length,0);assert.equal(view.project(runId)!.attempts.length,0);}
  else{await researchSettled(view,runId);const saved=view.project(runId),before=await snapshot(root);for(const command of ['/arbor export report','/arbor apply']){const denied=await client.command(command,r=>({value:r.options?.[0]}));assert.match(JSON.stringify(denied),/denied|approval|requires|permission/i);assert.ok(!denied.some(r=>r.method==='select'&&r.options?.includes('Apply exact source delta')),'Write denial must precede source approval');}assert.deepEqual(view.project(runId),saved);assert.deepEqual(await snapshot(root),before);}
  await inspect(client,runId);
 }});t.after(()=>h.store.close());assert.equal(h.value.p.attempts.length,boundary==='execute'?0:1);if(boundary==='execute')assert.equal(h.events.filter(e=>e.event==='native.result'&&['agents.create','agents.spawn'].includes(e.data.ref)).length,0);
 await appendFile(join(gates,'denials.jsonl'),JSON.stringify({root:h.root,boundary,attempts:h.value.p.attempts.length})+'\n');
});
test('PR12 actual pending review remains read-only until owning Pi answers',{timeout:240000},async t=>{
 const h=await host('command',{overrides:{objective:{description:'PR6_REQUEST_REVIEW',unit:'points'},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}},rpcJourney:async(client,root)=>{
  await client.command('/arbor start',respond);const view=new SourceView(join(root,'state')),runId=view.runs()[0]!.id;await researchSettled(view,runId);assert.equal(view.project(runId)!.run.state,'awaiting_review');
  // Read while pending, without steering which would intentionally stale the review.
  const notices=await client.command('/arbor browser',undefined,false),url=notices.find(r=>r.method==='notify'&&r.message.includes('browser:')).message.split('browser: ')[1];const browser=await chromium.launch();try{const page=await browser.newPage();const before=await snapshot(root);await page.goto(url);await page.waitForFunction(()=>document.getElementById('pending')!.textContent!.includes('Pending review:'));assert.match(await page.locator('#pending').innerText(),/cannot answer/);const saved=view.project(runId),base=new URL(url).origin;assert.deepEqual(await (await fetch(base+'/api/projection?run='+runId)).json(),saved);assert.equal((await fetch(base+'/api/review',{method:'POST',body:JSON.stringify({runId,approved:true})})).status,405);assert.equal((await fetch(base+'/api/projection?run='+runId+'&approved=true')).status,405);assert.equal(await page.getByRole('button',{name:/approve|reject/i}).count(),0);assert.deepEqual(view.project(runId),saved);await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await page.screenshot({path:join(root,'pr12-pending.png'),fullPage:true});assert.deepEqual(await snapshot(root),before);}finally{await browser.close();}
  const reviewed=await client.command('/arbor review',r=>({value:r.options?.find((o:string)=>o==='Approve research choice')}));assert.ok(reviewed.some(r=>r.method==='select'&&r.options.includes('Approve research choice')));assert.equal(view.project(runId)!.run.pendingDecisionId,null);await client.command('/arbor cancel');await inspect(client,runId);
 }});t.after(()=>h.store.close());const rpc=JSON.parse(await readFile(join(h.root,'pr12-rpc.json'),'utf8'));assert.equal(rpc.failure,undefined,h.root+': '+rpc.failure);assert.equal(h.value.p.run.state,'cancelled');await appendFile(join(gates,'native.jsonl'),JSON.stringify({root:h.root,pendingReview:true,revision:h.value.p.run.revision})+'\n');
});
