import assert from 'node:assert/strict';
import { readFile,writeFile,mkdir } from 'node:fs/promises';
import test from 'node:test';
import { host } from '../fixtures/pr6-host.js';
import { pr8Provider } from '../fixtures/pr8-proposal.js';
import { researchModel } from '../fixtures/pr6-model.js';
import { commandProgram,researchCommand } from '../../src/research/commands.js';
const start=commandProgram(researchCommand('start',JSON.stringify({runId:'research'}))),resume=commandProgram(researchCommand('resume','research'));
const bind=`const bind=(p,id)=>({runId:p.run.id,materialId:p.run.spec.source.materialId,epoch:p.run.epoch,revision:p.run.revision,commandId:id});const get=()=>tools.call({ref:'arbor.inspect',args:{runId:'research'}});`;
async function evidence(name:string,h:Awaited<ReturnType<typeof host>>){await mkdir('.runtime/pr8-gates',{recursive:true});await writeFile('.runtime/pr8-gates/'+name+'.json',JSON.stringify({root:h.root,value:h.value,dialogs:JSON.parse(await readFile(h.root+'/rpc-ui.json','utf8'))},null,2));}
for(const mode of ['auto','direction','review','collaborative'] as const)test(`PR8 actual native ${mode} research/control RPC review journey`,{timeout:180000},async t=>{
 const program=bind+`const before=await(async()=>{${start}})();let receipt;const spec=JSON.stringify(before.run.spec),epoch=before.run.epoch;if(before.run.pendingDecisionId){receipt=await tools.call({ref:'arbor.review',args:{...bind(before,'owner-review'),decisionId:before.run.pendingDecisionId}});await(async()=>{${resume}})();}const p=await get();return JSON.stringify({before:compactProjection(before),receipt,p:compactProjection(p),sameSpec:JSON.stringify(p.run.spec)===spec,sameEpoch:p.run.epoch===epoch,live:(await agents.members({scope:'local',kinds:['actor','agent']})).filter(m=>!['completed','failed','stopped','timed_out'].includes(m.status))});`;
 const h=await host('command',{program,providerSource:await pr8Provider(),...(mode==='auto'?{}:{rpcResponses:['Approve research choice']}),overrides:{objective:{description:'PR8 modes',unit:'points'},search:{mode,maxActorTurns:32},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}}});t.after(()=>h.store.close());
 assert.equal(h.value.p.run.state,'paused',h.root);assert.equal(h.value.p.attempts.length,1);assert.equal(h.value.p.evaluations.length,2);assert.equal(h.value.p.decisions.find((d:any)=>d.decisionId==='pr8-keep')?.status,'measured-keep');assert.ok(h.value.sameSpec&&h.value.sameEpoch);assert.deepEqual(h.value.live,[]);
 if(mode!=='auto'){assert.equal(h.value.before.run.state,'awaiting_review');assert.equal(h.value.before.attempts.length,mode==='review'?1:0);assert.equal(h.value.receipt.status,'applied');const d=h.value.p.decisions.find((d:any)=>d.decisionId==='pr8-choice');assert.equal(d.userReceipt.response,'Approve research choice');assert.deepEqual(d.userReceipt.owner,h.value.p.run.owner);assert.equal(d.userReceipt.materialId,h.value.p.run.spec.source.materialId);assert.equal(d.userReceipt.epoch,h.value.p.run.epoch);}
 await evidence('native-mode-'+mode,h);
});
test('PR8 actual owning-Pi steer/pause/reload/resume re-grounds saved roles/spec instead of changed defaults',{timeout:180000},async t=>{
 const program=bind+`const active=(async()=>{${start}})();await Promise.race([tools.call({ref:'pr2fixture.ready',args:{}}),active.then(()=>{throw new Error('Ask barrier absent')})]);let p=await get();await tools.call({ref:'arbor.control',args:{...bind(p,'steer'),action:'steer',instruction:'Retain the same fixed hypothesis and report exact limitations.'}});p=await get();const pause=await tools.call({ref:'arbor.control',args:{...bind(p,'pause'),action:'pause'}});await tools.call({ref:'pr2fixture.release',args:{}});await active;const before=await get();await pi.bash({command:'printf broken-new-defaults > arbor.config.json'});await components.reload({id:'arbor'});const after=await(async()=>{${resume}})();return JSON.stringify({before:compactProjection(before),p:compactProjection(after),pause,sameSpec:JSON.stringify(before.run.spec)===JSON.stringify(after.run.spec),live:(await agents.members({scope:'local',kinds:['actor','agent']})).filter(m=>!['completed','failed','stopped','timed_out'].includes(m.status))});`;
 const h=await host('command',{program,hold:'agents.ask',providerSource:await pr8Provider(),overrides:{objective:{description:'PR8 steer',unit:'points'},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}}});t.after(()=>h.store.close());assert.equal(h.value.before.run.state,'paused');assert.equal(h.value.before.attempts.length,0);assert.ok(h.value.sameSpec);assert.equal(h.value.p.attempts.length,1);assert.equal(h.value.p.decisions.find((d:any)=>d.decisionId==='pr8-keep')?.status,'measured-keep');assert.deepEqual(h.value.live,[]);assert.ok(h.events.some(e=>e.event==='actor.observed'&&e.data.data.steering.includes('Retain the same fixed hypothesis and report exact limitations.')));await evidence('native-steer-reload',h);
});
for(const writePolicy of ['deny','ask'] as const)test(`PR8 native Fabric write ${writePolicy} cannot be bypassed by a measured keep or source approval flag`,{timeout:180000},async t=>{
 const program=bind+`const p=await(async()=>{${start}})();let error;try{await tools.call({ref:'arbor.apply',args:{...bind(p,'apply-denied'),decisionId:'pr8-keep'}})}catch(e){error=String(e)}return JSON.stringify({p:compactProjection(await get()),error});`;
 const h=await host('command',{program,writePolicy,providerSource:await pr8Provider(),overrides:{objective:{description:'PR8 permission',unit:'points'},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}}});t.after(()=>h.store.close());assert.match(h.value.error,/denied|approval|permission|requires/i);assert.equal(h.value.p.decisions.find((d:any)=>d.decisionId==='pr8-keep')?.status,'measured-keep');await evidence('native-write-'+writePolicy,h);
});
test('PR8 actual owner source conflict preserves newer edits and still generates a retrievable baseline-relative export',{timeout:180000},async t=>{
 const program=bind+`const p=await(async()=>{${start}})();await pi.bash({command:'printf "NEWER USER EDIT\\n" > program.cjs'});const apply=await tools.call({ref:'arbor.apply',args:{...bind(p,'conflict-apply'),decisionId:'pr8-keep'}});const exported=await tools.call({ref:'arbor.export',args:{...bind(await get(),'conflict-export'),format:'json'}});return JSON.stringify({apply,exported,p:compactProjection(await get())});`;
 const h=await host('command',{program,expectedSource:'NEWER USER EDIT\n',rpcResponses:['Apply exact source delta'],providerSource:await pr8Provider(),overrides:{objective:{description:'PR8 conflict',unit:'points'},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}}});t.after(()=>h.store.close());assert.equal(h.value.apply.status,'blocked');assert.equal(h.value.exported.status,'applied');const e=JSON.parse(await readFile(h.value.exported.value.path,'utf8'));assert.match(e.materialDelta.patch,/score:2/);assert.doesNotMatch(e.materialDelta.patch,/NEWER USER EDIT|USER STAGED/);await evidence('native-conflict-export',h);
});
test('PR8 actual RPC timeout never approves or dispatches; pending exact choice retained',{timeout:180000},async t=>{
 const program=bind+`const before=await(async()=>{${start}})();let error;try{await tools.call({ref:'arbor.review',args:{...bind(before,'timeout'),decisionId:before.run.pendingDecisionId}});}catch(e){error=String(e)}return JSON.stringify({p:compactProjection(await get()),error});`;
 const h=await host('command',{program,providerSource:await pr8Provider(),rpcResponses:[null],overrides:{objective:{description:'PR8 timeout',unit:'points'},search:{mode:'direction'}}});t.after(()=>h.store.close());assert.match(h.value.error,/timed out|dismissed/);assert.equal(h.value.p.run.state,'awaiting_review');assert.equal(h.value.p.attempts.length,0);assert.equal(h.value.p.decisions[0].status,'pending');await evidence('native-timeout',h);
});
test('PR8 actual owner apply then undo uses distinct genuine UI receipts and restores dirty source',{timeout:180000},async t=>{
 const applyCommand=researchCommand('apply','research pr8-keep'),applyProgram=commandProgram(applyCommand),undoProgram=commandProgram(researchCommand('undo-apply','research '+applyCommand.args.commandId));
 const program=bind+`const before=await(async()=>{${start}})();const applied=await(async()=>{${applyProgram}})();const changed=await pi.read({path:before.run.spec.source.root+'/program.cjs'});const undone=await(async()=>{${undoProgram}})();return JSON.stringify({p:compactProjection(await get()),applied,undone,changed});`;
 const h=await host('command',{program,providerSource:await pr8Provider(),rpcResponses:['Apply exact source delta','Undo exact source delta'],overrides:{objective:{description:'PR8 apply',unit:'points'},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}}});t.after(()=>h.store.close());assert.equal(h.value.applied.status,'applied');assert.equal(h.value.undone.status,'applied');assert.match(h.value.changed,/score:2/);const dialogs=JSON.parse(await readFile(h.root+'/rpc-ui.json','utf8'));assert.equal(dialogs.length,2);assert.notEqual(dialogs[0].request.id,dialogs[1].request.id);await evidence('native-apply-undo',h);
});
for(const mode of ['continue-partial','restart-parent'] as const)test(`PR8 actual native ${mode} charges new invocation and re-grounds saved same hypothesis`,{timeout:180000},async t=>{
 const continuationProgram=commandProgram(researchCommand(mode,'research h1 The original worker edited the fixed candidate but failed its result contract. Keep the same hypothesis and '+(mode==='continue-partial'?'continue exactly its partial artifact.':'restart explicitly from its recorded parent, not the partial artifact.')));
 const program=bind+`const before=await(async()=>{${start}})();const partial=before.run.material.candidates[0];const continuation=await(async()=>{${continuationProgram}})();await(async()=>{${resume}})();const p=await get();return JSON.stringify({p:compactProjection(p),partial,continuation,prior:before.attempts[0],sameSpec:JSON.stringify(before.run.spec)===JSON.stringify(p.run.spec),live:(await agents.members({scope:'local',kinds:['actor','agent']})).filter(m=>!['completed','failed','stopped','timed_out'].includes(m.status))});`;
 const h=await host('command',{program,providerSource:await pr8Provider(),inference:trace=>researchModel(trace,{failAttempt:'h1'}),overrides:{objective:{description:'PR8 partial',unit:'points'},limits:{attempts:2,evaluatorCalls:20,activeMs:600000}}});t.after(()=>h.store.close());assert.ok(h.value.sameSpec);assert.equal(h.value.p.run.attemptsUsed,2);assert.deepEqual(h.value.p.attempts[0],h.value.prior);assert.equal(h.value.p.attempts[1].continuation.mode,mode);assert.equal(h.value.p.attempts[1].continuation.sourceOid,mode==='continue-partial'?h.value.partial.oid:h.value.partial.parent);assert.equal(h.value.p.decisions.find((d:any)=>d.decisionId==='pr8-keep').status,'measured-keep');assert.deepEqual(h.value.live,[]);await evidence(mode==='continue-partial'?'native-partial':'native-restart-parent',h);
});
