import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { host } from '../fixtures/pr6-host.js';
import { pr8Provider, pr8Proposal } from '../fixtures/pr8-proposal.js';
import { researchModel } from '../fixtures/pr6-model.js';
import { commandProgram, researchCommand } from '../../src/research/commands.js';
const start=commandProgram(researchCommand('start',JSON.stringify({runId:'research'}))),resume=commandProgram(researchCommand('resume','research'));
const bind=`const get=()=>tools.call({ref:'arbor.inspect',args:{runId:'research'}});const bind=(p,id)=>({runId:p.run.id,materialId:p.run.spec.source.materialId,epoch:p.run.epoch,revision:p.run.revision,commandId:id});`;
async function evidence(name:string,h:Awaited<ReturnType<typeof host>>){await mkdir('.runtime/pr8-gates',{recursive:true});await writeFile('.runtime/pr8-gates/'+name+'.json',JSON.stringify({root:h.root,value:h.value,dialogs:JSON.parse(await readFile(h.root+'/rpc-ui.json','utf8'))},null,2));}
// Observation-only middleware in this fixture copy. Never dispatches or mutates.
async function replayObservedProvider(){
 const source=await pr8Provider(),anchor='    if (!held && proxy.ref === process.env.ARBOR_PR2_HOLD) {';
 assert.equal(source.split(anchor).length,2);
 return source.replace('import { appendFileSync }','import { appendFileSync, readFileSync, readdirSync }').replace('export default function fake','import {createHash} from "node:crypto";\nexport default function fake').replace(anchor,`
    if(proxy.ref==='arbor.inspect'&&(proxy.result as any).run?.state==='awaiting_review'){
      const projection=proxy.result as any,run=projection.run,root=process.env.ARBOR_PR2_TRACE!.slice(0,process.env.ARBOR_PR2_TRACE!.lastIndexOf('/'));
      const events=readFileSync(process.env.ARBOR_PR2_TRACE!,'utf8').trim().split('\\n').map(line=>JSON.parse(line));
      const effectRefs=['agents.create','agents.ask','agents.spawn','agents.wait','agents.stop','agents.remove','arbor.runResearch','arbor.evaluate','arbor.dispatch','arbor.apply','arbor.undoApply','arbor.review','arbor.export','arbor.scaffold'];
      const sha=(data:any)=>createHash('sha256').update(data).digest('hex');
      trace('pr8.replay.snapshot',{revision:run.revision,databaseHash:sha(readFileSync(root+'/state/research.sqlite3')),inventory:readdirSync(root+'/state').sort(),projectionHash:sha(JSON.stringify(projection)),budgets:{attemptsUsed:run.attemptsUsed,active:run.active,activeMs:run.activeMs,activeSince:run.activeSince,evaluations:projection.evaluations},nativeEffects:Object.fromEntries(effectRefs.map(ref=>[ref,events.filter(e=>e.event==='native.result'&&e.data.ref===ref).length]))});
    }
`+anchor);
}
for(const mode of ['direction','review','collaborative'] as const)test(`PR8 pending ${mode} review reload reconciles without approval or dispatch`,{timeout:180000},async t=>{
 const review=commandProgram(researchCommand('review','research pr8-choice'));
 const recoveryRequest=researchCommand('resume','research'),recoveryResume=commandProgram(recoveryRequest),afterReviewResume=commandProgram(researchCommand('resume','research'));
 const program=bind+`const before=await(async()=>{${start}})();const stale={...bind(before,'old-review'),decisionId:before.run.pendingDecisionId};await components.reload({id:'arbor'});let resumeError,reviewError,staleError,receipt;try{await(async()=>{${recoveryResume}})()}catch(e){resumeError=String(e)}const reconciled=await get();const original=reconciled.controls.find(c=>c.commandId===${JSON.stringify(recoveryRequest.args.commandId)});const replayReceipt=await tools.call({ref:'arbor.control',args:{runId:original.runId,materialId:original.materialId,epoch:original.epoch,revision:original.revision,commandId:original.commandId,action:'resume'}});const replayUnchanged=JSON.stringify(await get())===JSON.stringify(reconciled);try{await tools.call({ref:'arbor.review',args:stale})}catch(e){staleError=String(e)}try{receipt=await(async()=>{${review}})();await(async()=>{${afterReviewResume}})()}catch(e){reviewError=String(e)}return JSON.stringify({before:compactProjection(before),reconciled:compactProjection(reconciled),p:compactProjection(await get()),resumeError,reviewError,staleError,receipt,replayReceipt,replayUnchanged});`;
 const h=await host('command',{program,providerSource:await replayObservedProvider(),rpcResponses:['Approve research choice'],overrides:{objective:{description:'PR8 pending reload',unit:'points'},search:{mode,maxActorTurns:32},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}}});t.after(()=>h.store.close());await evidence('reload-review-'+mode,h);
 assert.equal(h.value.resumeError,undefined,h.root);assert.equal(h.value.reviewError,undefined,h.root);assert.match(h.value.staleError,/Stale|generation/);
 assert.equal(h.value.replayUnchanged,true,'Exact closed control replay must not advance facts');
 const replayResults=h.events.filter(e=>e.event==='native.result'&&e.data.ref==='arbor.control'&&e.data.result.commandId===recoveryRequest.args.commandId);assert.equal(replayResults.length,2);assert.deepEqual(replayResults[0].data.result,replayResults[1].data.result);assert.deepEqual(h.value.replayReceipt,replayResults[0].data.result);
 const {before,reconciled,p}=h.value;
 const replaySnapshots=h.events.filter(e=>e.event==='pr8.replay.snapshot'&&e.data.revision===reconciled.run.revision).map(e=>e.data);assert.ok(replaySnapshots.length>=2,'Before and after exact replay observations');for(const snapshot of replaySnapshots)assert.deepEqual(snapshot,replaySnapshots[0],'Replay preserves database bytes/inventory, projection, budgets and every native effect counter');
 assert.equal(before.run.state,'awaiting_review');assert.notEqual(before.run.generation,reconciled.run.generation);assert.equal(reconciled.run.state,'awaiting_review');assert.equal(reconciled.run.pendingDecisionId,before.run.pendingDecisionId);assert.deepEqual(reconciled.run.spec,before.run.spec);assert.deepEqual(reconciled.run.owner,before.run.owner);assert.equal(reconciled.run.epoch,before.run.epoch);assert.deepEqual(reconciled.attempts,before.attempts);assert.deepEqual(reconciled.evaluations,before.evaluations);
 const pending=reconciled.decisions.find((d:any)=>d.decisionId==='pr8-choice');assert.equal(pending.status,'pending');assert.equal(pending.userReceipt,undefined);assert.equal(pending.revision,reconciled.run.revision);
 assert.equal(p.attempts.length,1);assert.equal(p.evaluations.length,2);assert.equal(p.decisions.find((d:any)=>d.decisionId==='pr8-keep')?.status,'measured-keep');assert.equal(h.value.receipt.status,'applied');
});
for(const gap of ['journal','receipt'] as const)test(`PR8 all-postimage ${gap} gap reload public recovery and undo`,{timeout:180000},async t=>{
 const applyCommand=researchCommand('apply','research pr8-keep'),operation=String(applyCommand.args.commandId),apply=commandProgram(applyCommand),recover=commandProgram(researchCommand('apply','research '+operation)),undo=commandProgram(researchCommand('undo-apply','research '+operation));
 const program=bind+`const before=await(async()=>{${start}})();let applyError,recoveryError,recovered,undone;try{await(async()=>{${apply}})()}catch(e){applyError=String(e)}const original=await pi.read({path:installedPackageRoot+'/../state/runs/research/workspace/source-operations/${operation}.json'});await components.reload({id:'arbor'});await(async()=>{${resume}})();try{recovered=await(async()=>{${recover}})();undone=await(async()=>{${undo}})()}catch(e){recoveryError=String(e)}return JSON.stringify({applyError,recoveryError,recovered,undone,original,p:compactProjection(await get())});`;
 const h=await host('command',{sourceCopy:true,program,providerSource:await pr8Provider(),rpcResponses:['Apply exact source delta','Apply exact source delta','Undo exact source delta'],overrides:{objective:{description:'PR8 postwrite reload',unit:'points'},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}},prepare:async root=>{
  const path=join(root,'app/src',gap==='journal'?'material/SourceApply.ts':'research/ResearchService.ts'),s=await readFile(path,'utf8'),anchor=gap==='journal'?'  this.#save(j);return j;\n }\n}':'return this.store.sourceReceipt(command,this.owner.generation,name,decisionId,';
  assert.equal(s.split(anchor).length,2);const marker=JSON.stringify(join(root,'postwrite-fault'));await writeFile(path,"import { existsSync as faultExists, writeFileSync as faultWrite } from 'node:fs';\n"+s.replace(anchor,`if(!faultExists(${marker})){faultWrite(${marker},'once');throw new Error('PR8 final ${gap} interruption');}\n`+anchor));
 }});t.after(()=>h.store.close());await evidence('reload-source-'+gap,h);
 assert.match(h.value.applyError,new RegExp('PR8 final '+gap));assert.equal(h.value.recoveryError,undefined,h.root);assert.equal(h.value.recovered.status,'applied');assert.equal(h.value.undone.status,'applied');
 const journal=JSON.parse(await readFile(join(h.root,'state/runs/research/workspace/source-operations',operation+'.json'),'utf8'));
 assert.equal(journal.state,'applied');assert.equal(journal.adoptions.length,1);assert.notEqual(journal.adoptions[0].generation,journal.intent.binding.generation);assert.notEqual(journal.adoptions[0].commandId,operation);assert.equal(journal.adoptions[0].response,'Apply exact source delta');assert.deepEqual(journal.adoptions[0].owner,journal.intent.binding.owner);assert.equal(journal.intent.operationId,operation);assert.equal(journal.intent.binding.commandId,operation);assert.equal(journal.intent.binding.response,'Apply exact source delta');
 assert.equal(h.value.p.attempts.length,1);assert.equal(h.value.p.evaluations.length,2);
 assert.equal(journal.identity,JSON.parse(h.value.original).identity);assert.deepEqual(journal.intent,JSON.parse(h.value.original).intent);assert.equal(JSON.parse(h.value.original).state,gap==='journal'?'writing':'applied');
});

for(const kind of ['command','agent-suite'] as const)test(`PR8 pending material ${kind} review reload has an inert public resume receipt`,{timeout:180000},async t=>{
 const review=commandProgram(researchCommand('review','research material-choice'));
 const program=bind+`await(async()=>{${start}})();const act=async(name,payload,id)=>tools.call({ref:'arbor.'+name,args:{...bind(await get(),id),payload}});await act('propose',{nodeId:'h1',type:'hypothesis',parentId:null,title:'Improve once',rationale:'PR6_LEVEL=1; edit only the assigned subject path',sourceRefs:[]},'material-node');await act('dispatch',{nodeId:'h1',attemptId:'h1'},'material-dispatch');await act('evaluate',{attemptId:'h1',evaluationId:'material-eval'},'material-evaluate');await act('decide',{nodeId:'h1',decisionId:'material-choice',decision:'request_review',evidenceIds:['material-eval']},'material-choice-request');const before=await get();await components.reload({id:'arbor'});let resumeError,reviewError,receipt,reviewReceipt;try{receipt=await(async()=>{${resume}})()}catch(e){resumeError=String(e)}const reconciled=await get();try{reviewReceipt=await(async()=>{${review}})();await act('decide',{nodeId:'h1',decisionId:'material-keep',decision:'keep',evidenceIds:['material-eval']},'material-keep-command')}catch(e){reviewError=String(e)}const summary=p=>({run:{state:p.run.state,generation:p.run.generation,revision:p.run.revision},attempts:p.attempts,evaluations:p.evaluations.map(e=>({id:e.id,state:e.state})),decisions:p.decisions});return JSON.stringify({before:summary(before),reconciled:summary(reconciled),p:summary(await get()),sameAttempts:JSON.stringify(before.attempts)===JSON.stringify(reconciled.attempts),sameEvaluations:JSON.stringify(before.evaluations)===JSON.stringify(reconciled.evaluations),resumeError,reviewError,receipt,reviewReceipt});`;
 const h=await host(kind,{program,rpcResponses:['Approve research choice'],overrides:{execution:'material',objective:{description:'PR8 material review reload',unit:kind==='command'?'points':'quality'},search:{mode:'review'},limits:{attempts:1,evaluatorCalls:30,activeMs:600000}}});t.after(()=>h.store.close());await evidence('reload-material-'+kind,h);
 assert.equal(h.value.sameAttempts,true);assert.equal(h.value.sameEvaluations,true); // compare complete native records before compacting output
 assert.equal(h.value.resumeError,undefined,h.root);assert.equal(h.value.reviewError,undefined,h.root);assert.equal(h.value.receipt.status,'applied');assert.equal(h.value.receipt.value.state,'awaiting_review');assert.equal(h.value.reconciled.run.state,'awaiting_review');assert.notEqual(h.value.before.run.generation,h.value.reconciled.run.generation);assert.deepEqual(h.value.before.attempts,h.value.reconciled.attempts);assert.deepEqual(h.value.before.evaluations,h.value.reconciled.evaluations);assert.equal(h.value.reconciled.decisions.find((d:any)=>d.decisionId==='material-choice').revision,h.value.reconciled.run.revision);assert.equal(h.value.reviewReceipt.status,'applied');assert.equal(h.value.p.decisions.find((d:any)=>d.decisionId==='material-keep').status,'measured-keep');
});
function nextProposal(d:any){
 const p=pr8Proposal(d);if(!d.decisions.some((v:any)=>v.decisionId==='pr8-done'))return p;
 const attempt=d.attempts.find((a:any)=>a.id==='h2'),e=d.evidence.find((e:any)=>e.id==='eval-h2');
 if(!d.nodes.some((n:any)=>n.nodeId==='h2')){p.kind='propose';p.payload={nodeId:'h2',type:'hypothesis',parentId:'direction',title:'Further improvement',rationale:'PR6_LEVEL=4; edit only the assigned subject path',sourceRefs:[]};}
 else if(!attempt){p.kind='dispatch';p.payload={nodeId:'h2',attemptId:'h2',selection:{...d.selection.eligible.find((n:any)=>n.nodeId==='h2'),reason:'Improve after resume'}};p.estimatedBudget.attempts=1;}
 else if(!e){p.kind='evaluate';p.payload={attemptId:'h2',evaluationId:'eval-h2'};p.estimatedBudget.evaluatorCalls=d.budgets.evaluationCapacity;}
 else if(!d.decisions.some((v:any)=>v.decisionId==='second-keep')){p.kind='decide';p.payload={nodeId:'h2',decisionId:'second-keep',decision:'keep',evidenceIds:[e.id]};p.expectedEvidence=[e.id];}
 else {p.kind='decide';p.payload={nodeId:null,decisionId:'second-stop',decision:'stop',evidenceIds:[]};}
 return p;
}
test('PR8 original postwrite intent adopts and undoes after resume keeps a newer incumbent',{timeout:180000},async t=>{
 const applyCommand=researchCommand('apply','research pr8-keep'),operation=String(applyCommand.args.commandId),apply=commandProgram(applyCommand),recover=commandProgram(researchCommand('apply','research '+operation)),undo=commandProgram(researchCommand('undo-apply','research '+operation));
 const provider=(await pr8Provider()).replace('export default function fake',nextProposal.toString()+'\nexport default function fake').replace('const p=pr8Proposal(data);','const p=nextProposal(data);');
 const program=bind+`const before=await(async()=>{${start}})();let applyError,recoveryError,recovered,undone;try{await(async()=>{${apply}})()}catch(e){applyError=String(e)}await components.reload({id:'arbor'});await(async()=>{${resume}})();const advanced=await get();try{recovered=await(async()=>{${recover}})();undone=await(async()=>{${undo}})()}catch(e){recoveryError=String(e)}return JSON.stringify({before:compactProjection(before),advanced:compactProjection(advanced),p:compactProjection(await get()),applyError,recoveryError,recovered,undone});`;
 const h=await host('command',{sourceCopy:true,program,providerSource:provider,rpcResponses:['Apply exact source delta','Apply exact source delta','Undo exact source delta'],overrides:{objective:{description:'PR8 newer incumbent recovery',unit:'points'},limits:{attempts:2,evaluatorCalls:30,activeMs:600000}},prepare:async root=>{
  const path=join(root,'app/src/material/SourceApply.ts'),s=await readFile(path,'utf8'),anchor='  this.#save(j);return j;\n }\n}',marker=JSON.stringify(join(root,'postwrite-fault'));assert.equal(s.split(anchor).length,2);await writeFile(path,"import { existsSync as faultExists, writeFileSync as faultWrite } from 'node:fs';\n"+s.replace(anchor,`if(!faultExists(${marker})){faultWrite(${marker},'once');throw new Error('PR8 final journal interruption');}\n`+anchor));
 }});t.after(()=>h.store.close());await evidence('reload-source-new-incumbent',h);
 assert.match(h.value.applyError,/PR8 final journal/);assert.equal(h.value.recoveryError,undefined,h.root);assert.notEqual(h.value.before.run.material.incumbent,h.value.advanced.run.material.incumbent);assert.equal(h.value.advanced.decisions.find((d:any)=>d.decisionId==='second-keep').status,'measured-keep');assert.equal(h.value.recovered.status,'applied');assert.equal(h.value.undone.status,'applied');assert.equal(h.value.p.run.material.incumbent,h.value.advanced.run.material.incumbent);assert.equal(h.value.p.attempts.length,2);
 const dialogs=JSON.parse(await readFile(h.root+'/rpc-ui.json','utf8'));for(const d of dialogs.slice(1)){assert.ok(d.request.title.includes('selected '+h.value.before.run.material.incumbent));assert.ok(!d.request.title.includes('selected '+h.value.advanced.run.material.incumbent));}
 const journal=JSON.parse(await readFile(h.value.recovered.value.path,'utf8'));assert.equal(journal.intent.target,h.value.before.run.material.incumbent);assert.equal(journal.intent.binding.decisionId,'pr8-keep');assert.equal(journal.adoptions[0].decisionId,operation);
});

test('PR8 native cancel during continuation collection cannot reopen cancelled research',{timeout:180000},async t=>{
 const restart=commandProgram(researchCommand('restart-parent','research h1 Restart this same hypothesis from its exact original parent.')),cancel=commandProgram(researchCommand('cancel','research'));
 const program=bind+`await(async()=>{${start}})();const pending=(async()=>{${restart}})();let cancelled;try{await pi.bash({command:'for i in {1..1500}; do if [ -f ../collection-ready ]; then exit 0; fi; sleep 0.01; done; exit 1'});await(async()=>{${cancel}})();cancelled=await get();}finally{await pi.bash({command:'touch ../collection-release'});await pending;}let resumeError;try{await(async()=>{${resume}})()}catch(e){resumeError=String(e)}return JSON.stringify({cancelled:compactProjection(cancelled),p:compactProjection(await get()),resumeError});`;
 const h=await host('command',{sourceCopy:true,program,providerSource:await pr8Provider(),inference:trace=>researchModel(trace,{failAttempt:'h1'}),overrides:{objective:{description:'PR8 cancellation collection',unit:'points'},limits:{attempts:2,evaluatorCalls:20,activeMs:600000}},prepare:async root=>{
  const path=join(root,'app/src/material/MaterialJourney.ts'),source=await readFile(path,'utf8'),anchor='try{const frozen=await workspace.freeze(m.capture,candidate);';assert.equal(source.split(anchor).length,2);
  const hold=`if(name==='resumeAttempt'){await new Promise<void>(resolve=>{const watcher=collectionWatch(${JSON.stringify(root)},()=>{if(collectionExists(${JSON.stringify(join(root,'collection-release'))})){watcher.close();resolve();}});collectionWrite(${JSON.stringify(join(root,'collection-ready'))},'held');if(collectionExists(${JSON.stringify(join(root,'collection-release'))})){watcher.close();resolve();}});}`;
  await writeFile(path,"import { watch as collectionWatch, existsSync as collectionExists, writeFileSync as collectionWrite } from 'node:fs';\n"+source.replace(anchor,'try{'+hold+anchor.slice(4)));
 }});t.after(()=>h.store.close());await evidence('native-continuation-cancel',h);
 assert.equal(h.value.cancelled.run.state,'cancelled');assert.equal(h.value.p.run.state,'cancelled');assert.equal(h.value.p.run.execution,'material-cancelled');assert.match(h.value.resumeError,/terminal|Terminal/);assert.equal(h.value.p.run.active,0);assert.deepEqual(h.value.p.attempts,h.value.cancelled.attempts);assert.deepEqual(h.value.p.evaluations,h.value.cancelled.evaluations);assert.equal(h.events.filter(e=>e.event==='native.result'&&e.data.ref==='agents.spawn').length,2);
});
test('PR8 native measured restart refines and discards after original prelaunch refusal',{timeout:180000},async t=>{
 const restart=commandProgram(researchCommand('restart-parent','research h1 Retry this same hypothesis from its saved parent after proven prelaunch refusal.')),cancel=commandProgram(researchCommand('pause','research'));
 const program=bind+`await(async()=>{${start}})();const act=async(name,payload,id)=>tools.call({ref:'arbor.'+name,args:{...bind(await get(),id),payload}});await act('propose',{nodeId:'h1',type:'hypothesis',parentId:null,title:'Original hypothesis',rationale:'PR6_LEVEL=1; edit only the assigned subject path',sourceRefs:[]},'original-node');let refusal;try{await act('dispatch',{nodeId:'h1',attemptId:'h1'},'original-dispatch')}catch(e){refusal=String(e)}await(async()=>{${cancel}})();const before=await get();await(async()=>{${restart}})();await(async()=>{${resume}})();const continued=await get(),attempt=continued.attempts.at(-1);await act('evaluate',{attemptId:attempt.id,evaluationId:'continued-eval'},'continued-evaluate');let refineError,discardError,refined,discarded;try{refined=await act('propose',{nodeId:'refined',type:'hypothesis',parentId:'h1',title:'Refine measured continuation',rationale:'Use exact linked continuation evidence',sourceRefs:[]},'refine')}catch(e){refineError=String(e)}try{discarded=await act('decide',{nodeId:'h1',decisionId:'discard-continuation',decision:'discard',evidenceIds:['continued-eval']},'discard')}catch(e){discardError=String(e)}return JSON.stringify({refusal,refineError,discardError,refined,discarded,prior:before.attempts[0],p:compactProjection(await get())});`;
 const h=await host('command',{program,overrides:{execution:'material',limits:{attempts:2,evaluatorCalls:20,activeMs:600000}},prepare:async root=>{const path=join(root,'state/runs/research/workspace/candidates/h1');await mkdir(path,{recursive:true});await writeFile(join(path,'retained'),'pre-existing obstruction');}});t.after(()=>h.store.close());await evidence('native-continuation-refine-discard',h);
 assert.match(h.value.refusal,/already exists|not empty/);assert.equal(h.value.refineError,undefined);assert.equal(h.value.discardError,undefined);assert.equal(h.value.refined.status,'applied');assert.equal(h.value.discarded.status,'applied');assert.deepEqual(h.value.p.attempts[0],h.value.prior);assert.equal(h.value.prior.nativeDigest,null);assert.equal(h.value.prior.nativeId,null);assert.equal(h.value.p.attempts[1].state,'completed');assert.ok(h.value.p.attempts[1].nativeDigest);assert.equal(h.value.p.attempts[1].continuation.mode,'restart-parent');assert.equal(h.value.p.run.active,0);assert.equal(h.events.filter(e=>e.event==='native.result'&&e.data.ref==='agents.spawn').length,1);assert.equal(await readFile(join(h.root,'state/runs/research/workspace/candidates/h1/retained'),'utf8'),'pre-existing obstruction');
});
for(const change of ['bytes','mode'] as const)test(`PR8 terminal source newer ${change} blocks recovery and undo`,{timeout:180000},async t=>{
 const applyCommand=researchCommand('apply','research pr8-keep'),operation=String(applyCommand.args.commandId),apply=commandProgram(applyCommand),cancel=commandProgram(researchCommand('cancel','research')),recover=commandProgram(researchCommand('apply','research '+operation)),undo=commandProgram(researchCommand('undo-apply','research '+operation));
 const edit=change==='bytes'?"printf 'NEWER USER EDIT\\n' > program.cjs":'chmod 755 program.cjs';
 const program=bind+`await(async()=>{${start}})();await(async()=>{${apply}})();await(async()=>{${cancel}})();const cancelled=await get();await components.reload({id:'arbor'});await pi.bash({command:${JSON.stringify(edit)}});let recoveryError,undoError,recovered,undone;try{undone=await(async()=>{${undo}})()}catch(e){undoError=String(e)}try{recovered=await(async()=>{${recover}})()}catch(e){recoveryError=String(e)}return JSON.stringify({recoveryError,undoError,recovered,undone,cancelled:compactProjection(cancelled),p:compactProjection(await get())});`;
 const h=await host('command',{program,providerSource:await pr8Provider(),expectedSource:change==='bytes'?'NEWER USER EDIT\n':'module.exports={level:1,score:2};\n',rpcResponses:['Apply exact source delta','Undo exact source delta','Apply exact source delta'],overrides:{objective:{description:'PR8 terminal source conflict',unit:'points'},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}}});t.after(()=>h.store.close());await evidence('terminal-source-newer-'+change,h);
 assert.equal(h.value.undoError,undefined);assert.equal(h.value.recoveryError,undefined);assert.equal(h.value.undone.status,'blocked');assert.equal(h.value.recovered.status,'blocked');assert.match(h.value.undone.reason,/conflict/i);assert.match(h.value.recovered.reason,/postimages|conflict/i);assert.equal(h.value.p.run.state,'cancelled');assert.equal(h.value.p.run.generation,h.value.cancelled.run.generation);assert.deepEqual(h.value.p.attempts,h.value.cancelled.attempts);assert.deepEqual(h.value.p.evaluations,h.value.cancelled.evaluations);
 if(change==='mode'){const {stat}=await import('node:fs/promises');assert.equal((await stat(join(h.root,'source/program.cjs'))).mode&0o777,0o755);}
});
test('PR8 terminal source different native owner and normal write deny ask remain blocked',{timeout:240000},async t=>{
 const applyCommand=researchCommand('apply','research pr8-keep'),operation=String(applyCommand.args.commandId),apply=commandProgram(applyCommand),cancel=commandProgram(researchCommand('cancel','research')),recover=commandProgram(researchCommand('apply','research '+operation)),undo=commandProgram(researchCommand('undo-apply','research '+operation));
 const h=await host('command',{program:bind+`await(async()=>{${start}})();await(async()=>{${apply}})();await(async()=>{${cancel}})();await components.reload({id:'arbor'});return JSON.stringify({p:compactProjection(await get())});`,providerSource:await pr8Provider(),expectedSource:'module.exports={level:1,score:2};\n',rpcResponses:['Apply exact source delta'],overrides:{objective:{description:'PR8 terminal source owner denial',unit:'points'},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}}});t.after(()=>h.store.close());
 const snapshot=JSON.stringify(h.store.projection('research')),journalPath=join(h.root,'state/runs/research/workspace/source-operations',operation+'.json'),journal=await readFile(journalPath,'utf8'),index=await readFile(join(h.root,'source/.git/index')),modules=resolve('node_modules'),manifest=JSON.parse(await readFile(join(modules,'pi-fabric/package.json'),'utf8')),env={...process.env};
 for(const key of Object.keys(env))if(key.startsWith('PI_')||key.startsWith('ARBOR_'))delete env[key];
 Object.assign(env,{HOME:join(h.root,'home'),PI_CODING_AGENT_DIR:join(h.root,'profile'),PI_OFFLINE:'1',PI_SKIP_VERSION_CHECK:'1',ARBOR_PR2_TRACE:join(h.root,'trace.jsonl'),ARBOR_PR2_PROGRAM:`const self=await agents.self(),errors=[];for(const action of [async()=>{${recover}},async()=>{${undo}}]){try{await action();errors.push(null)}catch(e){errors.push(String(e))}}return JSON.stringify({self,errors});`});
 const observations=[];
 for(const policy of ['allow','deny','ask']){
  const configPath=join(h.root,'source/.pi/fabric.json'),config=JSON.parse(await readFile(configPath,'utf8'));config.approvals.write=policy;await writeFile(configPath,JSON.stringify(config));
  const pending=promisify(execFile)(join(modules,'.bin/pi'),['--approve','--offline','--no-session','--no-skills','--no-prompt-templates','--no-themes','--provider','arbor-pr2-fake','--model','deterministic','--thinking','off','-e',resolve(modules,'pi-fabric',manifest.exports['.'].import),'-e',join(h.root,'profile/extensions/main.ts'),'--mode','json','-p','Observe retained terminal source intent without attachment'],{cwd:join(h.root,'source'),env,timeout:90000,maxBuffer:2*1048576});pending.child.stdin?.end();let failure:any;
  const out=await pending.catch(e=>{failure=e;return{stdout:e.stdout??'',stderr:e.stderr??String(e)}}),exit={code:pending.child.exitCode,signal:pending.child.signalCode,killed:pending.child.killed,error:failure?.message??null};
  await Promise.all([writeFile(join(h.root,policy+'-stdout.log'),out.stdout),writeFile(join(h.root,policy+'-stderr.log'),out.stderr),writeFile(join(h.root,policy+'-exit.json'),JSON.stringify(exit))]);assert.deepEqual(exit,{code:0,signal:null,killed:false,error:null},h.root);
  const events=(await readFile(join(h.root,'trace.jsonl'),'utf8')).trim().split('\n').map(l=>JSON.parse(l)),value=JSON.parse(events.filter(e=>e.event==='main.result').at(-1).data);observations.push({policy,exit,value});assert.notEqual(value.self.ownerHostId,h.value.p.run.owner.ownerHostId);assert.equal(value.errors.length,2);for(const error of value.errors)assert.match(error,policy==='allow'?/Different native owning Pi/:/denied|approval|permission|requires/i);
  assert.equal(events.filter(e=>e.event==='native.result'&&['agents.create','agents.spawn'].includes(e.data.ref)).length,2);assert.equal(JSON.stringify(h.store.projection('research')),snapshot);assert.equal(await readFile(journalPath,'utf8'),journal);assert.deepEqual(await readFile(join(h.root,'source/.git/index')),index);assert.equal(await readFile(join(h.root,'source/program.cjs'),'utf8'),'module.exports={level:1,score:2};\n');
 }
 await evidence('terminal-source-owner-policy',h);await writeFile('.runtime/pr8-gates/terminal-source-owner-policy-observations.json',JSON.stringify({root:h.root,observations},null,2));
});
for(const gap of ['applied','journal','receipt'] as const)test(`PR8 terminal source ${gap} cancel reload reconciles without reopening research`,{timeout:180000},async t=>{
 const applyCommand=researchCommand('apply','research pr8-keep'),operation=String(applyCommand.args.commandId),apply=commandProgram(applyCommand),recover=commandProgram(researchCommand('apply','research '+operation)),undo=commandProgram(researchCommand('undo-apply','research '+operation)),cancel=commandProgram(researchCommand('cancel','research'));
 const program=bind+`await(async()=>{${start}})();let applyError,recoveryError,resumeError,recovered,undone,newApplyError;try{await(async()=>{${apply}})()}catch(e){applyError=String(e)}const original=await pi.read({path:installedPackageRoot+'/../state/runs/research/workspace/source-operations/${operation}.json'});await(async()=>{${cancel}})();const cancelled=await get();await components.reload({id:'arbor'});const component=await components.status({id:'arbor'});try{await(async()=>{${resume}})()}catch(e){resumeError=String(e)}try{await tools.call({ref:'arbor.apply',args:{...bind(await get(),'new-terminal-apply'),decisionId:'pr8-keep'}})}catch(e){newApplyError=String(e)}try{${gap==='applied'?'':`recovered=await(async()=>{${recover}})();`}undone=await(async()=>{${undo}})()}catch(e){recoveryError=String(e)}return JSON.stringify({applyError,recoveryError,resumeError,newApplyError,recovered,undone,original,component,cancelled:compactProjection(cancelled),p:compactProjection(await get())});`;
 const h=await host('command',{sourceCopy:true,program,providerSource:await pr8Provider(),rpcResponses:['Apply exact source delta',...(gap==='applied'?[]:['Apply exact source delta']),'Undo exact source delta'],overrides:{objective:{description:'PR8 terminal source reload',unit:'points'},limits:{attempts:1,evaluatorCalls:20,activeMs:600000}},prepare:async root=>{
  if(gap==='applied')return;
  const path=join(root,'app/src',gap==='journal'?'material/SourceApply.ts':'research/ResearchService.ts'),s=await readFile(path,'utf8'),anchor=gap==='journal'?'  this.#save(j);return j;\n }\n}':'return this.store.sourceReceipt(command,this.owner.generation,name,decisionId,',marker=JSON.stringify(join(root,'terminal-postwrite-fault'));
  assert.equal(s.split(anchor).length,2);await writeFile(path,"import { existsSync as faultExists, writeFileSync as faultWrite } from 'node:fs';\n"+s.replace(anchor,`if(!faultExists(${marker})){faultWrite(${marker},'once');throw new Error('PR8 terminal ${gap} interruption');}\n`+anchor));
 }});t.after(()=>h.store.close());await evidence('terminal-source-'+gap,h);
 assert.equal(h.value.recoveryError,undefined,h.root);assert.match(h.value.resumeError,/terminal|Terminal/);assert.match(h.value.newApplyError,/Terminal source reconciliation requires an original apply intent/);assert.equal(h.value.undone.status,'applied');
 const {cancelled,p}=h.value;assert.equal(cancelled.run.state,'cancelled');assert.equal(p.run.state,'cancelled');assert.equal(p.run.generation,cancelled.run.generation);assert.deepEqual(p.run.spec,cancelled.run.spec);assert.deepEqual(p.run.owner,cancelled.run.owner);assert.equal(p.run.epoch,cancelled.run.epoch);assert.deepEqual(p.attempts,cancelled.attempts);assert.deepEqual(p.evaluations,cancelled.evaluations);assert.deepEqual(p.decisions,cancelled.decisions);assert.deepEqual(p.run.material,cancelled.run.material);assert.equal(p.run.active,0);
 const journal=JSON.parse(await readFile(join(h.root,'state/runs/research/workspace/source-operations',operation+'.json'),'utf8')),original=JSON.parse(h.value.original),undone=JSON.parse(await readFile(h.value.undone.value.path,'utf8'));
 assert.deepEqual(journal.intent,original.intent);assert.equal(journal.identity,original.identity);assert.equal(undone.intent.parent,operation);assert.notEqual(undone.intent.binding.generation,cancelled.run.generation);assert.deepEqual(undone.intent.binding.owner,cancelled.run.owner);assert.equal(undone.intent.binding.response,'Undo exact source delta');
 if(gap!=='applied'){assert.match(h.value.applyError,new RegExp('PR8 terminal '+gap));assert.equal(h.value.recovered.status,'applied');assert.equal(original.state,gap==='journal'?'writing':'applied');assert.equal(journal.adoptions.length,1);assert.equal(journal.adoptions[0].generation,undone.intent.binding.generation);}
 const effects=h.events.filter(e=>e.event==='native.result'&&['agents.create','agents.spawn'].includes(e.data.ref));assert.equal(effects.length,2,'Only original actor and worker, no terminal redispatch');
});
