import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFileSync,realpathSync,lstatSync,writeFileSync} from 'node:fs';
import {join,resolve,dirname,sep} from 'node:path';
import {ACTION_MANIFEST,canonical} from '../../src/research/contracts.js';
import {ARBOR_OWNER_REFS} from '../../src/managed/contracts.js';
import {validationSchema} from '../../src/package.js';
const app=process.cwd(),base='2cfc98c559bd357d8b75e8b44008f333ea0f5859',gates=join(app,'.runtime/pr10-gates');
const read=(p:string)=>readFileSync(p,'utf8'),json=(p:string)=>JSON.parse(read(p));
function gate(name:string,counts:number[],exit=false){const text=read(join(gates,name+'.log'));if(exit)assert.equal(read(join(gates,name+'.exit')).trim(),'0',name);for(const key of ['tests','pass','fail','cancelled','skipped','todo'])assert.deepEqual([...text.matchAll(new RegExp('ℹ '+key+' (\\d+)','g'))].map(m=>Number(m[1])),['tests','pass'].includes(key)?counts:counts.map(()=>0),name+': '+key);assert.equal([...text.matchAll(/ℹ duration_ms/g)].length,counts.length,name+': natural completion');return counts.reduce((a,b)=>a+b,0);}
const normal=gate('normal-final',[5,92,20,57,45,88]),targeted=gate('direction-review-green',[15]);
const native=Object.fromEntries([['native-pr10-final',4],['native-negative-experience-final',2],['native-collision-grounding-final',2],['native-pr6',21],['native-pr7',5],['native-pr8',42],['native-pr9',13]].map(([n,c])=>[n,gate(String(n),[Number(c)],true)]));
const manifest=json(join(app,'docs/pr3-action-manifest.json'));assert.equal(manifest.actions.length,20);assert.deepEqual(manifest.validationPolicy,validationSchema());for(const a of ACTION_MANIFEST)assert.equal(canonical(manifest.actions.find((m:any)=>m.ref===a.ref)),canonical(a));assert.equal(manifest.actions.find((a:any)=>a.ref==='arbor.lessons').risk,'read');
assert.deepEqual(ARBOR_OWNER_REFS,['agents.self','agents.members','agents.status','agents.create','agents.ask','agents.spawn','agents.wait','agents.stop','agents.remove','schema.status']);
const pkg=json(join(app,'package.json')),prior=JSON.parse(execFileSync('git',['show',`${base}:pi-fabric-arbor/package.json`],{encoding:'utf8'}));for(const key of ['dependencies','devDependencies','peerDependencies','exports','bin','pi'])assert.deepEqual(pkg[key],prior[key],key);assert.equal(pkg.pi.skills.length,1);assert.equal(pkg.scripts['test:source:retained'],prior.scripts['test:source:retained']);
for(const path of ['node_modules','node_modules/pi-fabric','node_modules/@earendil-works/pi-coding-agent']){assert.equal(lstatSync(join(app,path)).isSymbolicLink(),false,path);assert.equal(realpathSync(join(app,path)),join(app,path));}
const unchanged=['package-lock.json','src/managed/contracts.ts','src/material/Workspace.ts','src/material/SourceApply.ts','src/evaluators/material.ts','skills/fabric-arbor/SKILL.md','web/read-only','tests/integration/pr6-research-host.test.ts','tests/integration/pr7-parallel-host.test.ts','tests/integration/pr8-recovery-host.test.ts','tests/integration/pr9-held-out-host.test.ts','tests/git/fingerprint.test.ts'];assert.equal(execFileSync('git',['diff',base,'--',...unchanged],{encoding:'utf8'}),'');
const reachable=new Set<string>();function visit(path:string){path=resolve(path);if(reachable.has(path))return;reachable.add(path);assert.ok(path.startsWith(app+sep));assert.doesNotMatch(path.slice(app.length),/\/(?:certification|containment|phase7|pr0|fixtures)\//u);for(const m of read(path).matchAll(/(?:from\s*|import\s*)["']([^"']+)["']/gu)){const ref=m[1]!;if(ref.startsWith('.'))visit(resolve(dirname(path),ref.replace(/\.js$/u,'.ts')));else if(ref.startsWith('pi-fabric'))assert.ok(['pi-fabric','pi-fabric/protocol'].includes(ref),ref);}}
visit(join(app,'src/extension.ts'));
const raw=JSON.parse(execFileSync('npm',['pack','--dry-run','--ignore-scripts','--json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));const pack:any=Array.isArray(raw)?raw[0]:Object.values(raw)[0],paths=new Set<string>(pack.files.map((f:any)=>f.path));for(const path of reachable)assert.ok(paths.has(path.slice(app.length+1)),path);for(const path of paths)assert.doesNotMatch(path,/^(?:dist|\.test-dist|\.runtime|tests|node_modules)\//u);for(const path of ['src/research/Grounding.ts','src/research/SourceCatalog.ts','src/research/GroundingContracts.ts','src/research/schema.ts','skills/fabric-arbor/roles/literature.md','docs/pr10-grounding-evidence.md'])assert.ok(paths.has(path));
for(const mode of [[],['--mode','attached'],['--mode','offline']]){let denied=false;try{execFileSync(process.execPath,['bin/pi-fabric-arbor.mjs','export',...mode],{encoding:'utf8',stdio:'pipe'});}catch(error){const e=error as {status:number;stderr:string};assert.equal(e.status,2);assert.match(String(e.stderr),/strictly read-only/);denied=true;}assert.ok(denied);}
let maxEventBytes=0;const roots:string[]=[];for(const file of ['native-experience.jsonl','native-grounding.jsonl']){const latest=new Map<boolean,any>();for(const line of read(join(gates,file)).trim().split('\n')){const entry=JSON.parse(line);latest.set(entry.installed,entry);}assert.equal(latest.size,2);for(const e of latest.values()){for(const root of [e.root,...(e.discovery?[e.discovery]:[])]){assert.ok(resolve(root).startsWith(join(app,'.runtime')+sep));assert.deepEqual(json(join(root,'exit.json')),{code:0,signal:null,killed:false,error:null});roots.push(root);for(const line of read(join(root,'trace.jsonl')).trim().split('\n'))maxEventBytes=Math.max(maxEventBytes,Buffer.byteLength(line));}}}assert.ok(maxEventBytes<=65536);
const timing=json(join(app,'.runtime/pr7-gates/a12.json'));assert.ok(timing.ratio<=.8);for(const r of timing.results){assert.equal(r.warmed.length,3);assert.equal(r.waves.length,4);assert.ok(r.waves.every((w:any)=>w.attemptIds.length===2));if(r.concurrency===2)assert.ok(r.warmed.every((w:any)=>w.overlap>0));}
const evidence={normal,targeted,native,actions:20,ownerRequirements:10,publicSkills:1,reachableModules:reachable.size,packedFiles:paths.size,maxEventBytes,nativeRoots:roots,a12:{ratio:timing.ratio,serialMs:timing.results[0].median,parallelMs:timing.results[1].median},scope:'PR10 deterministic local gate; independent review and publication evidence recorded separately'};writeFileSync(join(gates,'audit.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({...evidence,nativeRoots:roots.length}));
