import assert from 'node:assert/strict';
import {mkdir,mkdtemp,writeFile,unlink,symlink,rename} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import test from 'node:test';
import {ResearchStore,type ResearchRun} from '../../src/research/ResearchStore.js';
import {resolveSpec} from '../../src/research/spec.js';
import {digest,canonical,validate} from '../../src/research/contracts.js';
import {SourceCatalog} from '../../src/research/SourceCatalog.js';
import {Grounding} from '../../src/research/Grounding.js';
import {literatureResultSchema,sourceSearchInputSchema,sourceSearchOutputSchema,sourceFetchInputSchema,sourceFetchOutputSchema} from '../../src/research/GroundingContracts.js';
async function fixture(t:test.TestContext){
 const base=resolve('.runtime/pr10-unit');await mkdir(base,{recursive:true});const root=await mkdtemp(join(base,'delayed-')),store=new ResearchStore(join(root,'research.sqlite3'));t.after(()=>store.close());
 const spec=await resolveSpec(root,{},{},{execution:'deferred'},'fake/coordinator');spec.config.grounding={mode:'optional',catalog:'public',query:null,maxSources:2,model:null};
 const run:ResearchRun={id:'run',spec,requestHash:'run',owner:{id:'root',rootId:'root',ownerHostId:'host',ownerIdentityId:'owner',sessionId:'session'},componentId:'arbor.owner',generation:'g1',epoch:'epoch-1',revision:0,state:'ready',attemptsUsed:0,active:0,createdAt:1,activeMs:0,activeSince:null,steering:[],pendingDecisionId:null,execution:'not-started',error:null};store.create(run);
 const command=(id='grounding',runId='run')=>store.binding(store.get(runId)!,id);store.reserveGrounding(command(),'g1',digest('catalog'));
 const text='Visited article. Caching avoids repeated parsing.',path=join(root,'passage.txt');await writeFile(path,text);
 for(const id of ['one','sibling']){const r=store.get('run')!;store.recordSourceAccess(command(),'g1',{id,kind:'source-access',runId:r.id,materialId:r.spec.source.materialId,epoch:r.epoch,specId:r.spec.identity,generation:r.generation,revision:r.revision,catalogId:digest('catalog'),url:'https://example.test/'+id,title:id,artifact:{path,digest:digest(text)},search:{ref:'public.search',binding:'binding',requestId:digest('query'),resultId:digest('search')},fetch:{ref:'public.fetch',binding:'binding',requestId:digest('url'),resultId:digest('fetch')},characters:text.length,validation:'visited-not-yet-inspected'});}
 const native={value:{sentinel:'ARBOR_LITERATURE_RESULT_V1' as const,batchId:store.get('run')!.grounding!.batchId,sources:['one','sibling'].map(accessId=>({accessId,passage:'Caching avoids repeated parsing.',claim:'Test cache',limitations:'Retest locally'})),blocked:null},nativeId:'native',requestId:digest('native'),roleBundleId:'roles-'+digest('roles'),model:'fake/literature'};
 const complete=()=>store.completeGrounding(command(),'g1',native);
 const ref=(s:any)=>({sourceId:s.id,runId:s.runId,revision:s.revision,digest:s.digest});
 const prepare=()=>{complete();const sources=(store.projection('run')!.artifact_refs as any[]).filter(a=>a.kind==='source-inspection');for(const [id,parentId,type,groundingRefs] of [['direction',null,'direction',[]],['leaf','direction','hypothesis',[ref(sources[0])]],['sibling','direction','hypothesis',[ref(sources[1])]]] as const)store.research('propose',command(id),{nodeId:id,parentId,type,title:id,rationale:'Retest',sourceRefs:[],groundingRefs},'g1');store.research('dispatch',command('dispatch'),{nodeId:'leaf',attemptId:'attempt'},'g1');store.native('run','attempt','g1',{id:'native-attempt',cwd:root,status:'completed'});return sources;};
 const distill=()=>store.research('distill',command('distill'),{lessonId:'lesson',nodeId:'direction',insight:'cache parser',limitations:'Retest',evidenceIds:[store.attempt('run','attempt')!.evidenceId]},'g1');
 return {root,store,run,command,text,path,native,complete,prepare,distill,ref};
}
for(const field of ['passage','claim','limitations'] as const)test('PR10 delayed nonwhitespace '+field,async t=>{const f=await fixture(t),native=structuredClone(f.native);native.value.sources[0]![field]=' \t\n ';const before=canonical(f.store.projection('run'));assert.throws(()=>f.store.completeGrounding(f.command(),'g1',native));assert.equal(canonical(f.store.projection('run')),before);assert.throws(()=>validate(literatureResultSchema(),native.value));const schema=literatureResultSchema().properties!.sources!.items!.properties![field]!;assert.ok(schema.pattern && !new RegExp(schema.pattern,'u').test(' '),'Native JSON schema must reject whitespace');});
for(const change of ['stale','delete','path'] as const)test('PR10 delayed exact sources revalidated before distill '+change,async t=>{const f=await fixture(t);f.prepare();const before=canonical(f.store.projection('run'));if(change==='stale')await writeFile(f.path,'changed');else if(change==='delete')await unlink(f.path);else{await rename(f.path,f.path+'.moved');await symlink(f.path+'.moved',f.path);}assert.throws(f.distill,/source|artifact|ENOENT/i);assert.equal(canonical(f.store.projection('run')),before);});
for(const change of ['stale','delete','path'] as const)test('PR10 delayed exact source references survive distill and fence cross-run recall '+change,async t=>{const f=await fixture(t),sources=f.prepare();f.distill();const lesson=(f.store.projection('run')!.lessons as any[])[0];assert.deepEqual(lesson.provenance.sourceRefs,[f.ref(sources[0])]);assert.deepEqual(lesson.provenance.sourceIds,[sources[0].id]);f.store.create({...f.run,id:'next',requestHash:'next'});const hit=f.store.lessons({runId:'next',query:'cache',limit:8})[0]!;assert.ok(hit);const before=canonical([f.store.projection('run'),f.store.projection('next')]);if(change==='stale')await writeFile(f.path,'changed');else if(change==='delete')await unlink(f.path);else{await rename(f.path,f.path+'.moved');await symlink(f.path+'.moved',f.path);}assert.deepEqual(f.store.lessons({runId:'next',query:'cache',limit:8}),[]);assert.throws(()=>f.store.research('propose',f.command('retest','next'),{nodeId:'retest',parentId:null,type:'hypothesis',title:'Retest',rationale:'Retest',sourceRefs:[],lessonRefs:[hit.reference]},'g1'));assert.equal(canonical([f.store.projection('run'),f.store.projection('next')]),before);});
test('PR10 delayed completed native grounding reaches replay without source redispatch',async t=>{const f=await fixture(t);let calls=0;const owner={generation:'g1',inspectLiterature:async()=>{calls++;return f.native;}};assert.equal(await new Grounding(owner as any,f.store,f.root).run('run',{} as any),true);assert.equal(calls,1);assert.equal(f.store.get('run')!.grounding!.status,'complete');});
test('PR10 delayed source catalog nested expected snapshots cannot widen',()=>{const entries=[{id:'public',search:{ref:'public.search',descriptorHash:'a'.repeat(64)},fetch:{ref:'public.fetch',descriptorHash:'b'.repeat(64)}}],view={bindings:{'public.search':{descriptorHash:'a'.repeat(64),effect:{resources:['original']}}},data:{refs:['original']}} as any;const c=new SourceCatalog(entries,view,async()=>null),before=canonical({entries:c.entries,view:c.view,id:c.id,binding:c.binding('public','search')});entries[0]!.search.ref='evil.search';view.bindings['public.search'].effect.resources.push('evil');view.data.refs.push('evil');assert.equal(canonical({entries:c.entries,view:c.view,id:c.id,binding:c.binding('public','search')}),before);for(const mutate of [()=>{c.entries[0]!.search.ref='evil.search'},()=>{(c.entries as any).push(entries[0])},()=>{(c.view as any).bindings['public.search'].descriptorHash='b'.repeat(64)},()=>{(c.view as any).bindings['public.search'].effect.resources.push('evil')},()=>{(c.view as any).data.refs.push('evil')},()=>{c.binding('public','search').cap.ref='evil.search'}]){try{mutate();}catch{}assert.equal(canonical({entries:c.entries,view:c.view,id:c.id,binding:c.binding('public','search')}),before);}});
for(const kind of ['search','fetch'] as const)test('PR10 delayed '+kind+' reply aliases cannot poison captured value or provenance',async()=>{
 const hash='a'.repeat(64),entries=[{id:'public',search:{ref:'public.search',descriptorHash:hash},fetch:{ref:'public.fetch',descriptorHash:hash}}],view={bindings:{'public.search':{descriptorHash:hash},'public.fetch':{descriptorHash:hash}}} as any;
 const input=kind==='search'?sourceSearchInputSchema():sourceFetchInputSchema(),output=kind==='search'?sourceSearchOutputSchema():sourceFetchOutputSchema(),args=kind==='search'?{query:'cache',limit:1}:{url:'https://example.test/article',maxChars:100};
 const reply:any=kind==='search'?{results:[{url:'https://example.test/article',title:'Original',snippet:'Discovery'}]}:{url:args.url,title:'Original',text:'Visited source'};
 const catalog=new SourceCatalog(entries,view,async()=>reply,async()=>({name:kind,description:kind,inputSchema:input,outputSchema:output,risk:'read',effect:{kind:'none',resources:[],ordering:'commutative'}}));
 const captured=await catalog.invoke('public',kind,args,async()=>{}),before=canonical(captured);if(kind==='search'){reply.results[0].title='POISON';reply.results.push({url:'https://evil.test',title:'POISON',snippet:'POISON'});assert.throws(()=>captured.value.results.push(reply.results[1]));}else{reply.text='POISON';assert.throws(()=>{captured.value.text='POISON';});}
 assert.equal(canonical(captured),before);assert.equal(captured.provenance.resultId,digest(captured.value));
 let calls=0;const guarded=new SourceCatalog(entries,view,async()=>{calls++;return reply;},async()=>({name:kind,description:kind,inputSchema:input,outputSchema:output,risk:'read',effect:{kind:'none',resources:[],ordering:'commutative'}}));await assert.rejects(guarded.invoke('public',kind,args,async()=>{if(kind==='search')args.query='POISON';else args.url='https://evil.test';}),/mutated/);assert.equal(calls,0);
});
