import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFileSync,realpathSync,lstatSync,writeFileSync} from 'node:fs';
import {join,resolve,dirname,sep} from 'node:path';
import {ACTION_MANIFEST,canonical,validate} from '../../src/research/contracts.js';
import {ARBOR_OWNER_REFS} from '../../src/managed/contracts.js';
import {ARBOR_PACKAGED_ASSETS,presetSchema,packManifestSchema,readPackManifest,SCAFFOLD_SCHEMA} from '../../src/package.js';
const app=process.cwd(),base='c8abf2a20e4d72d495cb744ec6589909ee2f4f1c',gates=join(app,'.runtime/pr11-gates');
const read=(p:string)=>readFileSync(p,'utf8'),json=(p:string)=>JSON.parse(read(p));
function gate(name:string,counts:number[],exit=false){const text=read(join(gates,name+'.log'));if(exit)assert.equal(read(join(gates,name+'.exit')).trim(),'0',name);for(const key of ['tests','pass','fail','cancelled','skipped','todo'])assert.deepEqual([...text.matchAll(new RegExp('ℹ '+key+' (\\d+)','g'))].map(m=>Number(m[1])),['tests','pass'].includes(key)?counts:counts.map(()=>0),name+': '+key);assert.equal([...text.matchAll(/ℹ duration_ms/g)].length,counts.length,name+': natural completion');return counts.reduce((a,b)=>a+b,0);}
const normal=gate('normal-final',[5,92,20,71,45,88]),targeted=gate('targeted-final',[14]);
const native=Object.fromEntries([['native-pr11-limits-final',8],['native-overflow-final',1],['native-pr6',21],['native-pr7',5],['native-pr8',42],['native-pr9',13],['native-pr10',4]].map(([n,c])=>[n,gate(String(n),[Number(c)],true)]));
const manifest=json(join(app,'docs/pr3-action-manifest.json'));assert.equal(manifest.actions.length,21);assert.deepEqual(manifest.preset,presetSchema());assert.deepEqual(manifest.exampleManifest,packManifestSchema());for(const a of ACTION_MANIFEST)assert.equal(canonical(manifest.actions.find((m:any)=>m.ref===a.ref)),canonical(a));const scaffold=manifest.actions.find((a:any)=>a.ref==='arbor.scaffold');assert.equal(scaffold.risk,'write');assert.equal(scaffold.caller,'owning-Pi');assert.equal(scaffold.actorCommitment,false);assert.deepEqual(scaffold.inputSchema,SCAFFOLD_SCHEMA);assert.deepEqual(scaffold.commands,['/arbor scaffold']);
assert.deepEqual(ARBOR_OWNER_REFS,['agents.self','agents.members','agents.status','agents.create','agents.ask','agents.spawn','agents.wait','agents.stop','agents.remove','schema.status']);
const pkg=json(join(app,'package.json')),prior=JSON.parse(execFileSync('git',['show',`${base}:pi-fabric-arbor/package.json`],{encoding:'utf8'}));for(const key of ['dependencies','devDependencies','peerDependencies','exports','bin','pi'])assert.deepEqual(pkg[key],prior[key],key);assert.equal(pkg.pi.skills.length,1);assert.equal(pkg.scripts['test:source:retained'],prior.scripts['test:source:retained']);assert.ok(pkg.scripts['test:pr3'].includes('tests/research/*.test.ts'));assert.match(pkg.scripts['test:source'],/test:pr3/);assert.match(pkg.scripts['test:pr11:e2e'],/pr11-examples-host/);for(const key of ['build','prepack','prepare'])assert.equal(pkg.scripts[key],undefined);
for(const path of ['node_modules','node_modules/pi-fabric','node_modules/@earendil-works/pi-coding-agent']){assert.equal(lstatSync(join(app,path)).isSymbolicLink(),false,path);assert.equal(realpathSync(join(app,path)),join(app,path));}
const unchanged=['package-lock.json','src/managed/contracts.ts','src/material/Workspace.ts','src/material/SourceApply.ts','src/evaluators/material.ts','skills/fabric-arbor/SKILL.md','skills/fabric-arbor/roles','web/read-only','tests/fixtures/pr6-host.ts','tests/fixtures/pr6-model.ts','tests/fixtures/pr2-fake-provider.ts','tests/integration/pr6-research-host.test.ts','tests/integration/pr7-parallel-host.test.ts','tests/integration/pr8-recovery-host.test.ts','tests/integration/pr9-held-out-host.test.ts','tests/integration/pr10-grounding-host.test.ts','tests/git/fingerprint.test.ts'];assert.equal(execFileSync('git',['diff',base,'--',...unchanged],{encoding:'utf8'}),'');
const reachable=new Set<string>();function visit(path:string){path=resolve(path);if(reachable.has(path))return;reachable.add(path);assert.ok(path.startsWith(app+sep));assert.doesNotMatch(path.slice(app.length),/\/(?:certification|containment|phase7|pr0|fixtures)\//u);for(const m of read(path).matchAll(/(?:from\s*|import\s*)["']([^"']+)["']/gu)){const ref=m[1]!;if(ref.startsWith('.'))visit(resolve(dirname(path),ref.replace(/\.js$/u,'.ts')));else if(ref.startsWith('pi-fabric'))assert.ok(['pi-fabric','pi-fabric/protocol'].includes(ref),ref);}}
for(const path of ['src/extension.ts','src/package.ts','src/cli/read-only.ts'])visit(join(app,path));
const raw=JSON.parse(execFileSync('npm',['pack','--dry-run','--ignore-scripts','--json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));const pack:any=Array.isArray(raw)?raw[0]:Object.values(raw)[0],paths=new Set<string>(pack.files.map((f:any)=>f.path));for(const path of reachable)assert.ok(paths.has(path.slice(app.length+1)),path);for(const path of paths)assert.doesNotMatch(path,/^(?:dist|\.test-dist|\.runtime|tests|node_modules)\//u);for(const path of Object.values(ARBOR_PACKAGED_ASSETS))assert.ok(paths.has(path),path);
const packs=await readPackManifest();assert.deepEqual(packs.packs.map((p:any)=>p.id),['code','agent','recipe']);for(const p of packs.packs){assert.ok(paths.has('examples/'+p.preset));validate(presetSchema(),json(join(app,'examples',p.preset)));for(const file of p.files)assert.ok(paths.has(`examples/${p.id}/${file}`));for(const file of [...p.mutablePaths,...p.evaluationInputs])assert.ok(p.files.includes(file));}assert.ok(paths.has('examples/agent/tasks.json'));assert.ok(paths.has('docs/pr11-examples-evidence.md'));
for(const mode of [[],['--mode','attached'],['--mode','offline']])for(const verb of ['scaffold','prepare','init','create','create-export','export']){let denied=false;try{execFileSync(process.execPath,['bin/pi-fabric-arbor.mjs',verb,...mode],{encoding:'utf8',stdio:'pipe'});}catch(error){const e=error as {status:number;stderr:string};assert.equal(e.status,2);assert.match(String(e.stderr),/strictly read-only/);denied=true;}assert.ok(denied);}
let maxEventBytes=0;const latest=new Map<string,any>();for(const line of read(join(gates,'native-examples.jsonl')).trim().split('\n')){const e=JSON.parse(line);latest.set(e.pack+':'+e.installed,e);}assert.equal(latest.size,6);const roots:string[]=[];for(const e of latest.values()){assert.ok(resolve(e.root).startsWith(join(app,'.runtime')+sep));assert.deepEqual(json(join(e.root,'exit.json')),{code:0,signal:null,killed:false,error:null});assert.equal(e.preparation.status,'unvalidated');assert.notEqual(e.baseline,e.incumbent);assert.ok(e.analysis.wins>0);assert.ok(e.accountedCalls>=e.measurementInvocations);roots.push(e.root);for(const line of read(join(e.root,'trace.jsonl')).trim().split('\n'))maxEventBytes=Math.max(maxEventBytes,Buffer.byteLength(line));if(e.installed){const installed=join(e.root,'node_modules/pi-fabric-arbor');assert.equal(realpathSync(installed),installed);for(const path of Object.values(ARBOR_PACKAGED_ASSETS))assert.ok(lstatSync(join(installed,path)).isFile(),path);}}
const overflow=JSON.parse(read(join(gates,'native-overflow.jsonl')).trim().split('\n').at(-1)!);assert.ok(resolve(overflow.root).startsWith(join(app,'.runtime')+sep));assert.deepEqual(json(join(overflow.root,'exit.json')),{code:0,signal:null,killed:false,error:null});assert.match(overflow.error,/Evaluation definition exceeds bound/);roots.push(overflow.root);
assert.ok(maxEventBytes<=65536);
const timing=json(join(app,'.runtime/pr7-gates/a12.json'));assert.ok(timing.ratio<=.8);for(const r of timing.results){assert.equal(r.warmed.length,3);assert.equal(r.waves.length,4);assert.ok(r.waves.every((w:any)=>w.attemptIds.length===2));if(r.concurrency===2)assert.ok(r.warmed.every((w:any)=>w.overlap>0));}
const evidence={normal,targeted,native,actions:21,ownerRequirements:10,publicSkills:1,reachableModules:reachable.size,packedFiles:paths.size,maxEventBytes,nativeRoots:roots,a12:{ratio:timing.ratio,serialMs:timing.results[0].median,parallelMs:timing.results[1].median},scope:'PR11 deterministic local packs; upstream template unvalidated; independent review and publication recorded separately'};writeFileSync(join(gates,'audit.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({...evidence,nativeRoots:roots.length}));
