import {manifest as generatedManifest} from './export-manifest.js';
import ts from 'typescript';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readFileSync,realpathSync,lstatSync,writeFileSync} from 'node:fs';
import {join,resolve,dirname,sep} from 'node:path';
import {ACTION_MANIFEST,canonical} from '../../src/research/contracts.js';
import {ARBOR_OWNER_REFS} from '../../src/managed/contracts.js';
import {ARBOR_PACKAGED_ASSETS} from '../../src/package.js';
const app=process.cwd(),base='823f5490e86179391505710ff66e7bd580e8aa92',gates=join(app,'.runtime/pr12-gates');
const read=(p:string)=>readFileSync(p,'utf8'),json=(p:string)=>JSON.parse(read(p));
const prior=(p:string)=>execFileSync('git',['show',`${base}:pi-fabric-arbor/${p}`],{encoding:'utf8'});
const hash=(path:string)=>createHash('sha256').update(readFileSync(path)).digest('hex');
function gate(name:string,counts:number[]){const text=read(join(gates,name+'.log'));assert.equal(read(join(gates,name+'.exit')).trim(),'0',name);for(const key of ['tests','pass','fail','cancelled','skipped','todo'])assert.deepEqual([...text.matchAll(new RegExp('ℹ '+key+' (\\d+)','g'))].map(m=>Number(m[1])),['tests','pass'].includes(key)?counts:counts.map(()=>0),name+': '+key);assert.equal([...text.matchAll(/ℹ duration_ms/g)].length,counts.length,name+': natural completion');return counts.reduce((a,b)=>a+b,0);}
const normal=gate('final-normal-approved',[5,92,36,120,45,93]),targeted=gate('final-targeted-approved',[41]);
const native=Object.fromEntries([['final-native-pr12',35],['current-final-native-pr2',8],['current-native-pr3',20],['reconciled-native-pr4',21],['current-final-native-pr5',9],['current-final-native-pr6',21],['final-native-pr7',5],['final-native-pr8-reconciled',42],['final-native-pr9',13],['final-native-pr10',4],['final-native-pr11',9]].map(([n,c])=>[n,gate(String(n),[Number(c)])]));
const lifetime=json(join(app,'.runtime/pr12-design/approved-lifetime-audit.json'));assert.equal(lifetime.status,'PASS');assert.equal(lifetime.nativeTests,35);assert.equal(lifetime.targetedTests,41);for(const [path,expected] of Object.entries(lifetime.modules))assert.equal(hash(join(app,path)),expected,'Current scoped lifetime module: '+path);
const manifest=json(join(app,'docs/pr3-action-manifest.json'));assert.deepEqual(manifest,generatedManifest,'Complete generated public contract including command/configuration metadata');assert.equal(manifest.actions.length,21);assert.deepEqual(manifest.internalCapabilities,generatedManifest.internalCapabilities);assert.deepEqual(manifest.ownerProvides,['arbor','arbor_lifetime']);assert.deepEqual(manifest.drainRequires,['arbor_lifetime.lease']);for(const a of ACTION_MANIFEST)assert.equal(canonical(manifest.actions.find((m:any)=>m.ref===a.ref)),canonical(a));
assert.deepEqual(ARBOR_OWNER_REFS,['agents.self','agents.members','agents.status','agents.create','agents.ask','agents.spawn','agents.wait','agents.stop','agents.remove','schema.status']);
const pkg=json(join(app,'package.json')),old=JSON.parse(prior('package.json'));
for(const key of ['dependencies','peerDependencies','exports','bin','pi'])assert.deepEqual(pkg[key],old[key],key);
assert.deepEqual(pkg.devDependencies,{...old.devDependencies,playwright:'1.63.0'});assert.equal(pkg.pi.skills.length,1);
for(const [name,script] of Object.entries(old.scripts)){const expected=name==='test:pr10'?String(script).replace('tests/research/pr10-experience.test.ts','tests/research/pr10-delayed.test.ts tests/research/pr10-experience.test.ts'):script;assert.equal(pkg.scripts[name],expected,'Preserve every old case; only add the delayed PR10 regression: '+name);}
assert.ok(pkg.scripts['test:pr3'].includes('tests/research/*.test.ts'));for(const key of ['build','prepack','prepare'])assert.equal(pkg.scripts[key],undefined);
const lock=json(join(app,'package-lock.json')),oldLock=JSON.parse(prior('package-lock.json'));
assert.deepEqual(lock.packages[''],{...oldLock.packages[''],devDependencies:pkg.devDependencies});
for(const [path,entry] of Object.entries(oldLock.packages))if(path)assert.deepEqual(lock.packages[path],entry,'No hidden old module change: '+path);
assert.deepEqual(Object.keys(lock.packages).filter(p=>!Object.hasOwn(oldLock.packages,p)).sort(),['node_modules/playwright','node_modules/playwright-core']);
for(const path of ['node_modules/playwright','node_modules/playwright-core']){assert.equal(lock.packages[path].dev,true);assert.equal(lock.packages[path].version,'1.63.0');}
for(const path of ['node_modules','node_modules/pi-fabric','node_modules/@earendil-works/pi-coding-agent','node_modules/playwright'])assert.equal(realpathSync(join(app,path)),join(app,path));
const unchanged=['src/managed/contracts.ts','src/material/Workspace.ts','src/material/SourceApply.ts','src/evaluators/material.ts','skills/fabric-arbor/roles','tests/fixtures/pr6-model.ts','tests/fixtures/pr2-fake-provider.ts','tests/integration/pr7-parallel-host.test.ts','tests/integration/pr7-controls-host.test.ts','tests/integration/pr7-repairs-host.test.ts','tests/integration/pr8-controls-host.test.ts','tests/integration/pr8-recovery-host.test.ts','tests/integration/pr9-held-out-host.test.ts','tests/integration/pr10-experience-host.test.ts','tests/integration/pr11-examples-host.test.ts','tests/git/fingerprint.test.ts'];
assert.equal(execFileSync('git',['diff',base,'--',...unchanged],{encoding:'utf8'}),'');
// Preserve every executable prior assertion and test registration, rather than
// requiring obsolete fixture command construction to remain byte-identical.
function callTexts(source:string,kind:'assert'|'test'):string[]{const file=ts.createSourceFile('fixture.ts',source,ts.ScriptTarget.Latest,true),out:string[]=[];function walk(node:ts.Node){if(ts.isCallExpression(node)){const expression=node.expression.getText(file);if(kind==='assert'&&(expression==='assert'||expression.startsWith('assert.')))out.push(node.getText(file));if(kind==='test'&&expression==='test')out.push(node.arguments[0]!.getText(file));}ts.forEachChild(node,walk);}walk(file);return out;}
function preserveAssertions(path:string,replacements:Record<string,string>={}){const before=prior(path),after=read(join(app,path));for(const [prefix] of Object.entries(replacements))assert.equal(callTexts(before,'assert').filter(call=>call.startsWith(prefix)).length,1,'One characterized oracle: '+path+prefix);for(const kind of ['assert','test'] as const){const available=new Map<string,number>();for(const call of callTexts(after,kind))available.set(call,(available.get(call)??0)+1);for(const original of callTexts(before,kind)){const replacement=kind==='assert'?Object.entries(replacements).find(([prefix])=>original.startsWith(prefix))?.[1]:undefined,call=replacement??original;assert.ok((available.get(call)??0)>0,'Preserve executable '+kind+' in '+path+': '+call);available.set(call,available.get(call)!-1);}}return {path,priorAssertions:callTexts(before,'assert').length,characterizedOracles:Object.keys(replacements).length,sha256:hash(join(app,path))};}
const reconciledAssertions=[
 preserveAssertions('tests/integration/pr6-research-host.test.ts'),
 preserveAssertions('tests/integration/pr8-crash-host.test.ts',{'assert.match(h.value.error,':'assert.match(h.value.error,/Different native|Research resume intent owner unavailable/)'}),
 preserveAssertions('tests/fixtures/pr8-crash.ts',{'assert.match(value.error,':'assert.match(value.error,/Different native|Research resume intent owner unavailable/)'}),
 preserveAssertions('tests/integration/pr8-reload-regressions.test.ts'),
 preserveAssertions('tests/integration/pr10-grounding-host.test.ts'),
];
function requireSource(path:string,anchors:string[]){const source=read(join(app,path));for(const anchor of anchors)assert.ok(source.includes(anchor),'Required mechanical invariant '+path+': '+anchor);}
requireSource('tests/integration/pr6-research-host.test.ts',["const resumes=Array.from({length:3},()=>commandProgram(researchCommand('resume','research')))",'resumes.map(resume=>']);
requireSource('tests/integration/pr8-reload-regressions.test.ts',[
 "recoveryRequest=researchCommand('resume','research')","afterReviewResume=commandProgram(researchCommand('resume','research'))",
 "runId:original.runId,materialId:original.materialId,epoch:original.epoch,revision:original.revision,commandId:original.commandId,action:'resume'",
 'assert.equal(h.value.replayUnchanged,true,','assert.deepEqual(replayResults[0].data.result,replayResults[1].data.result)','assert.deepEqual(h.value.replayReceipt,replayResults[0].data.result)',
 "databaseHash:sha(readFileSync(root+'/state/research.sqlite3'))","inventory:readdirSync(root+'/state').sort()",'projectionHash:sha(JSON.stringify(projection))',
 'budgets:{attemptsUsed:run.attemptsUsed,active:run.active,activeMs:run.activeMs,activeSince:run.activeSince,evaluations:projection.evaluations}',
 'nativeEffects:Object.fromEntries(effectRefs.map','replaySnapshots.length>=2','assert.deepEqual(snapshot,replaySnapshots[0],',
]);
requireSource('tests/fixtures/pr8-crash.ts',[
 'assert.notEqual(value.self.ownerHostId,value.owner.ownerHostId)',"assert.equal(canonical(store.projection('research')),snapshot)",
 'assert.deepEqual(await readFile(store.path),databaseBytes)',"assert.deepEqual((await readdir(join(root,'state'))).sort(),inventory)",'assert.equal(count(events),count(priorEvents))',
]);
// Independently reread the successful native exact-replay observations. These
// hashes/counters come from read-only middleware, never fabricated dispatch.
for(const mode of ['direction','review','collaborative']){const proof=json(join(app,'.runtime/pr8-gates/reload-review-'+mode+'.json'));assert.deepEqual(json(join(proof.root,'exit.json')),{code:0,signal:null,killed:false,error:null});assert.equal(proof.value.resumeError,undefined);assert.equal(proof.value.reviewError,undefined);assert.equal(proof.value.replayUnchanged,true);const events=read(join(proof.root,'trace.jsonl')).trim().split('\n').map(line=>JSON.parse(line));const snapshots=events.filter(e=>e.event==='pr8.replay.snapshot'&&e.data.revision===proof.value.reconciled.run.revision).map(e=>e.data);assert.ok(snapshots.length>=2);assert.match(snapshots[0].databaseHash,/^[a-f0-9]{64}$/);assert.match(snapshots[0].projectionHash,/^[a-f0-9]{64}$/);for(const snapshot of snapshots)assert.deepEqual(snapshot,snapshots[0],'Exact replay byte/inventory/projection/budget/native-effect preservation: '+mode);const receipts=events.filter(e=>e.event==='native.result'&&e.data.ref==='arbor.control'&&e.data.result.commandId===proof.value.replayReceipt.commandId);assert.equal(receipts.length,2);for(const receipt of receipts)assert.deepEqual(receipt.data.result,proof.value.replayReceipt);}
for(let stage=1;stage<=9;stage++){const proof=json(join(app,`.runtime/pr8-gates/gap-${stage}.json`));assert.equal(proof.stage,stage);assert.notEqual(proof.value.self.ownerHostId,proof.value.owner.ownerHostId);assert.match(proof.value.error,/Different native|Research resume intent owner unavailable/);assert.equal(proof.value.denials.length,3);for(const denial of proof.value.denials)assert.match(denial.error,/Different native/);}
requireSource('tests/integration/pr10-grounding-host.test.ts',["commandProgram(researchCommand('resume','research'))","['missing-binding','missing-handle','unresolved','task','request','epoch','model','owner','bundle','result']",'assert.deepEqual(await effects(),beforeEffects,','assert.deepEqual(bindings[0]!.literatureResult,crashNative)']);
const retained=[...old.scripts['test:source:retained'].matchAll(/(?:tests\/[^ '\n]+\.ts)/g)].map(m=>m[0]);for(const path of retained)assert.equal(execFileSync('git',['diff',base,'--',path],{encoding:'utf8'}),'',path);
const host=read(join(app,'tests/fixtures/pr6-host.ts')),oldHost=prior('tests/fixtures/pr6-host.ts');assert.ok(host.includes(' const events=')&&oldHost.includes(' const events='));assert.equal(host.slice(host.indexOf(' const events=')),oldHost.slice(oldHost.indexOf(' const events=')),'Prior host final assertions remain exact');
const reachable=new Set<string>();function visit(path:string){path=resolve(path);if(reachable.has(path))return;reachable.add(path);assert.ok(path.startsWith(app+sep));assert.doesNotMatch(path.slice(app.length),/\/(?:certification|containment|phase7|pr0|fixtures)\//u);for(const m of read(path).matchAll(/(?:from\s*|import\s*)["']([^"']+)["']/gu)){const ref=m[1]!;if(ref.startsWith('.'))visit(resolve(dirname(path),ref.replace(/\.js$/u,'.ts')));else if(ref.startsWith('pi-fabric'))assert.ok(['pi-fabric','pi-fabric/protocol'].includes(ref),ref);}}
for(const path of ['src/extension.ts','src/package.ts','src/cli/read-only.ts'])visit(join(app,path));
const raw=JSON.parse(execFileSync('npm',['pack','--dry-run','--ignore-scripts','--json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));const pack:any=Array.isArray(raw)?raw[0]:Object.values(raw)[0],paths=new Set<string>(pack.files.map((f:any)=>f.path));
for(const path of reachable)assert.ok(paths.has(path.slice(app.length+1)),path);for(const path of paths)assert.doesNotMatch(path,/^(?:dist|\.test-dist|\.runtime|tests|node_modules)\//u);for(const path of Object.values(ARBOR_PACKAGED_ASSETS))assert.ok(paths.has(path),path);
assert.deepEqual([...paths].filter(p=>p.endsWith('/SKILL.md')),['skills/fabric-arbor/SKILL.md']);assert.equal([...paths].filter(p=>p.startsWith('skills/fabric-arbor/roles/')&&p.endsWith('.md')).length,3);
for(const path of ['skills/fabric-arbor/SKILL.md','docs/role-maintenance.md',...Object.values(ARBOR_PACKAGED_ASSETS).filter(p=>p.startsWith('skills/'))])for(const m of read(join(app,path)).matchAll(/\]\(([^)#]+)(?:#[^)]*)?\)/g)){if(/^[a-z]+:/i.test(m[1]!))continue;const target=resolve(dirname(join(app,path)),m[1]!);assert.ok(paths.has(target.slice(app.length+1)),'Packaged link: '+path+' -> '+m[1]);}
assert.equal([...read(join(app,'docs/role-maintenance.md')).matchAll(/^\| arbor-/gm)].length,11);
for(const mode of [[],['--mode','attached'],['--mode','offline']])for(const verb of ['setup','scaffold','start','pause','resume','cancel','steer','keep','discard','review','apply','undo-apply','export','validate','continue-partial','restart-parent','revise-roles','control','dispatch','evaluate','serve'])assert.throws(()=>execFileSync(process.execPath,['bin/pi-fabric-arbor.mjs',verb,...mode],{encoding:'utf8',stdio:'pipe'}),(e:any)=>e.status===2&&String(e.stderr).includes('strictly read-only'));
const rows=(name:string)=>read(join(gates,name+'.jsonl')).trim().split('\n').filter(Boolean).map(l=>JSON.parse(l));const latest=new Map<string,any>();for(const row of rows('native'))latest.set(row.pendingReview?'pending':row.installed?'installed':'source',row);assert.equal(latest.size,3);
const browsers=rows('browser'),proofs:Array<{root:string;label:string;revision:number;screenshots:Array<{path:string;sha256:string}>}>=[];
for(const [label,n] of latest){assert.ok(resolve(n.root).startsWith(join(app,'.runtime')+sep));assert.deepEqual(json(join(n.root,'exit.json')),{code:0,signal:null,killed:false,error:null});assert.equal(json(join(n.root,'pr12-rpc.json')).failure,undefined);
 let shots:string[];if(label==='pending')shots=[join(n.root,'pr12-pending.png')];else{assert.deepEqual(n.journeys,[1,2,3,4,5,6,7,8,9]);const b=browsers.findLast(b=>b.root===n.root&&b.label===label);assert.ok(b,'Browser proof must match successful native root');assert.ok(b.revision<b.finalRevision&&b.finalRevision<n.revision);assert.ok(b.attempts===4&&b.exports>=4);assert.deepEqual(b.errors,[]);assert.deepEqual(b.requestMethods,['GET']);for(const key of ['noninterference','lateCandidate','lateReplay','lateRefreshError','sse'])assert.equal(b[key],true,key);shots=b.screenshots;assert.ok(shots.some(p=>p.endsWith('pr12-final-tree.png')));}
 const screenshots=shots.map(path=>{assert.equal(dirname(path),n.root);assert.ok(lstatSync(path).isFile());assert.equal(readFileSync(path).subarray(0,8).toString('hex'),'89504e470d0a1a0a');return {path,sha256:hash(path)};});proofs.push({root:n.root,label,revision:n.revision,screenshots});
 if(label==='installed'){const installed=join(n.root,'node_modules/pi-fabric-arbor');assert.equal(realpathSync(installed),installed);for(const path of [...reachable].map(p=>p.slice(app.length+1)).concat(Object.values(ARBOR_PACKAGED_ASSETS)))assert.equal(hash(join(installed,path)),hash(join(app,path)),'Installed current source/asset: '+path);}}
const denialRoots=rows('denials').slice(-2);assert.deepEqual(denialRoots.map(r=>r.boundary).sort(),['execute','write']);for(const d of denialRoots){assert.ok(resolve(d.root).startsWith(join(app,'.runtime')+sep));assert.deepEqual(json(join(d.root,'exit.json')),{code:0,signal:null,killed:false,error:null});assert.equal(json(join(d.root,'pr12-rpc.json')).failure,undefined);assert.equal(d.attempts,d.boundary==='execute'?0:1);}
const recent=(name:string,key:(r:any)=>string)=>[...new Map(rows(name).map(r=>[key(r),r])).values()];
const clean=(r:any)=>{assert.deepEqual(json(join(r.root,'exit.json')),{code:0,signal:null,killed:false,error:null});assert.equal(json(join(r.root,'pr12-rpc.json')).failure,undefined);};
const activeRoots=recent('active-controls',r=>`${r.installed}/${r.hold}`).filter(r=>r.hold);assert.equal(activeRoots.length,4);for(const r of activeRoots){clean(r);assert.equal(r.mainAcknowledged,true);assert.equal(r.controlPolicy,'ordinary-tools');assert.equal(r.reviewed,true);assert.equal(r.reviewRunId,'review-run');assert.equal(r.state,'cancelled');assert.equal(r.active,0);}
const asks=recent('held-ask',r=>String(r.installed));assert.deepEqual(asks.map(r=>r.installed).sort(),[false,true]);for(const r of asks)clean(r);
const reloads=recent('held-reload',r=>`${r.installed}/${r.hold}`).filter(r=>r.hold);assert.equal(reloads.length,4);for(const r of reloads){clean(r);assert.equal(r.actualReload,true);assert.equal(r.heldSettlement,true);assert.equal(r.active,0);}
const providerDenials=recent('provider-denials',r=>`${r.installed}/${r.deny}`);assert.equal(providerDenials.length,4);for(const r of providerDenials){clean(r);assert.equal(r.evaluations,0);assert.equal(r.externalCalls,0);}
const agentPolicy=recent('agent-policy',r=>`${r.installed}/${r.policy}`);assert.equal(agentPolicy.length,4);for(const r of agentPolicy){clean(r);assert.equal(r.nativeEffects,0,'Agent policy must deny captured native effects');}
const timing=json(join(app,'.runtime/pr7-gates/a12.json'));assert.ok(timing.ratio<=.8);for(const r of timing.results){assert.equal(r.warmed.length,3);assert.equal(r.waves.length,4);assert.ok(r.waves.every((w:any)=>w.attemptIds.length===2));if(r.concurrency===2)assert.ok(r.warmed.every((w:any)=>w.overlap>0));}
const evidence={base,normal,targeted,native,reconciledAssertions,scopedLifetime:lifetime.status,actions:21,scopedCapabilities:1,ownerRequirements:10,publicSkills:1,internalRoles:3,upstreamDispositions:11,retained:92,fingerprintSha256:hash(join(app,'tests/git/fingerprint.test.ts')),reachableModules:reachable.size,packedFiles:paths.size,proofs,a12:{ratio:timing.ratio,serialMs:timing.results[0].median,parallelMs:timing.results[1].median},boundaries:'Deterministic local native inference. Source/installed nine journeys, pending review, GET-only reads, exact current projection, no research/control/material/ref/export writes. Cold reads preserve complete SQLite byte/inventory state, including raced WAL admission. Lifetime settlement is limited to the explicitly tested application/whole-Pi paths. No paid research, PR13 deletion or runtime cleanup. Independent review/publication recorded separately.'};
writeFileSync(join(gates,'audit.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({...evidence,proofs:proofs.map(p=>({label:p.label,root:p.root,screenshots:p.screenshots.length}))}));
