import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,realpathSync,existsSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {cutover,documentation} from '../fixtures/pr13-cutover.js';
import {ARBOR_PACKAGED_ASSETS} from '../../src/package.js';
import {manifest} from './export-manifest.js';
const app=process.cwd(),gates=join(app,'.runtime/pr13-gates'),base='b509ae7ccb1db2da02272d9eb9d304267c59119f';
const json=(p:string)=>JSON.parse(readFileSync(p,'utf8')),sha=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex');
function gate(name:string,counts:number[]){assert.equal(readFileSync(join(gates,name+'.exit'),'utf8').trim(),'0',name);const text=readFileSync(join(gates,name+'.log'),'utf8');for(const key of ['tests','pass','fail','cancelled','skipped','todo'])assert.deepEqual([...text.matchAll(new RegExp('ℹ '+key+' (\\d+)','g'))].map(m=>Number(m[1])),['tests','pass'].includes(key)?counts:counts.map(()=>0),name+': '+key);assert.equal([...text.matchAll(/ℹ duration_ms/g)].length,counts.length);return counts.reduce((a,b)=>a+b,0);}
const normal=gate('normal',[9,36,121,48,94]),targeted=gate('targeted',[9]),native=gate('native',[35,9]),structure=cutover(app,true);
assert.deepEqual(json(join(app,'docs/pr3-action-manifest.json')),manifest);
const priorNative=Object.fromEntries([[2,8],[3,20],[4,21],[5,9],[6,21],[7,5],[8,42],[9,13],[10,4]].map(([pr,count])=>[String(pr),gate('native-pr'+pr,[count!])]));
const timing=json(join(app,'.runtime/pr7-gates/a12.json'));assert.ok(timing.ratio<=.8);for(const r of timing.results){assert.equal(r.warmed.length,3);assert.equal(r.waves.length,4);assert.ok(r.waves.every((w:any)=>w.attemptIds.length===2));if(r.concurrency===2)assert.ok(r.warmed.every((w:any)=>w.overlap>0));}
for(const path of execFileSync('git',['ls-files','--','tests/integration','tests/fixtures'],{encoding:'utf8'}).trim().split('\n').filter(p=>p&&!p.includes('pr13-'))){const bytes=execFileSync('git',['show',base+':pi-fabric-arbor/'+path]);assert.equal(sha(join(app,path)),createHash('sha256').update(bytes).digest('hex'),'Retain native workload/assertions: '+path);}

const removed=execFileSync('git',['diff','--name-only','--diff-filter=D',base,'--','.'],{encoding:'utf8'}).trim().split('\n').filter(Boolean);assert.ok(removed.length>=280);assert.ok(removed.every(p=>p.startsWith('pi-fabric-arbor/')&&!p.includes('/.runtime/')));for(const p of removed)assert.equal(existsSync(resolve(app,'..',p)),false,p);
for(const p of structure.modules){const prior=execFileSync('git',['show',base+':pi-fabric-arbor/'+p]);assert.equal(sha(join(app,p)),createHash('sha256').update(prior).digest('hex'),'Cutover must not rewrite accepted production behavior: '+p);}
const pkg=json(join(app,'package.json')),old=JSON.parse(execFileSync('git',['show',base+':pi-fabric-arbor/package.json'],{encoding:'utf8'}));for(const key of ['dependencies','peerDependencies','devDependencies','exports','bin','pi'])assert.deepEqual(pkg[key],old[key]);assert.equal(sha(join(app,'package-lock.json')),createHash('sha256').update(execFileSync('git',['show',base+':pi-fabric-arbor/package-lock.json'])).digest('hex'));
const raw=JSON.parse(execFileSync('npm',['pack','--dry-run','--ignore-scripts','--json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']})),pack:any=Array.isArray(raw)?raw[0]:Object.values(raw)[0],packed=new Set<string>(pack.files.map((f:any)=>f.path));for(const p of structure.modules.concat(Object.values(ARBOR_PACKAGED_ASSETS)))assert.ok(packed.has(p),p);for(const p of packed)assert.doesNotMatch(p,/^(?:dist|\.test-dist|tests|certification|scripts|browser-tests|\.runtime|node_modules)\//);
for(const p of packed)if(p.endsWith('.md')){const text=readFileSync(join(app,p),'utf8');for(const m of text.matchAll(/npm run ([a-z0-9:-]+)/g))assert.ok(pkg.scripts[m[1]!],'Stale shipped command '+p+': '+m[1]);}
gate('package-final',[9]);
const documentationProof=documentation(app,packed);
const oldNotices=execFileSync('git',['show',base+':pi-fabric-arbor/THIRD_PARTY_NOTICES.md'],{maxBuffer:4*1024*1024}),notices=readFileSync(join(app,'THIRD_PARTY_NOTICES.md'));const attribution=(bytes:Buffer)=>createHash('sha256').update(bytes.subarray(bytes.indexOf('\n## '))).digest('hex');assert.equal(attribution(notices),attribution(oldNotices),'Retain every attribution byte, including original line endings');
const install=json(join(gates,'install.json'));assert.equal(realpathSync(install.installed),install.installed);cutover(install.installed);documentation(install.installed,packed);for(const p of packed){if(p==='src/package-layout.ts')assert.equal(readFileSync(join(install.installed,p),'utf8'),readFileSync(join(app,p),'utf8').replace('pr1-source-a','pr1-source-b'),'Only the deliberately reloaded sentinel may differ');else assert.equal(sha(join(install.installed,p)),sha(join(app,p)),'Exact clean-installed shipped bytes: '+p);}for(const p of packed)if(p.endsWith('.md'))for(const m of readFileSync(join(install.installed,p),'utf8').matchAll(/npm run ([a-z0-9:-]+)/g))assert.ok(pkg.scripts[m[1]!],'Stale clean-installed command '+p+': '+m[1]);assert.equal(install.passive,true);assert.equal(install.reloadedSource,true);
const rows=readFileSync(join(app,'.runtime/pr12-gates/native.jsonl'),'utf8').trim().split('\n').map(line=>JSON.parse(line)),installed=rows.findLast(r=>r.installed&&!r.pendingReview);assert.ok(installed);assert.deepEqual(json(join(installed.root,'exit.json')),{code:0,signal:null,killed:false,error:null});const installedRoot=join(installed.root,'node_modules/pi-fabric-arbor');cutover(installedRoot);for(const p of structure.modules.concat(Object.values(ARBOR_PACKAGED_ASSETS)))assert.equal(sha(join(installedRoot,p)),sha(join(app,p)),'Current clean-installed bytes: '+p);
const result={status:'PASS',base,normal,targeted,native,priorNative,allNative:native+Object.values(priorNative).reduce((a,b)=>a+b,0),documentation:documentationProof,a12:{ratio:timing.ratio,serialMs:timing.results[0].median,parallelMs:timing.results[1].median},deleted:removed.length,productionModules:structure.modules.length,packedFiles:packed.size,ordinaryRefs:21,scopedRefs:1,publicSkills:1,internalRoles:3,examples:3,install:install.installed,nativeInstalled:installedRoot,limits:'Fresh source-only product; no migration/history/certification prerequisites. All 43 accepted production modules unchanged. Deterministic local native/browser/pack evidence, not scientific validation. Existing runtime/user data untouched; only tracked package-owned legacy files removed. Approved application/whole-Pi lifetime scopes only.'};writeFileSync(join(gates,'audit.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
