import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,realpathSync,existsSync} from 'node:fs';
import {resolve,dirname,join} from 'node:path';
import {ARBOR_ACTIONS,ARBOR_OWNER_REFS} from '../../src/managed/contracts.js';
const app=process.cwd(),gate='.runtime/pr8-gates',read=(p:string)=>readFileSync(p,'utf8'),json=(p:string)=>JSON.parse(read(p)),git=(...args:string[])=>execFileSync('git',args,{encoding:'utf8'});
assert.equal(realpathSync(app),'/home/balauru/.pi-profiles/fabric/.worktrees/arbor-refactor/pi-fabric-arbor');assert.equal(git('branch','--show-current').trim(),'arbor/refactor-pr0-pr1');const base='f1c816c5e54218066b99cf45fafce80b18afad11';git('merge-base','--is-ancestor',base,'HEAD');
const pkg=json('package.json'),prior=JSON.parse(git('show',base+':pi-fabric-arbor/package.json'));
for(const field of ['dependencies','devDependencies','peerDependencies','pi'])assert.deepEqual(pkg[field],prior[field]);assert.equal(pkg.scripts['test:source:retained'],prior.scripts['test:source:retained']);
for(const path of ['package-lock.json','src/git/fingerprint.ts','tests/git/fingerprint.test.ts','skills/fabric-arbor/SKILL.md'])assert.equal(read(path),git('show',base+':pi-fabric-arbor/'+path),path);
for(const path of ['node_modules','node_modules/pi-fabric','node_modules/@earendil-works/pi-coding-agent'])assert.equal(realpathSync(path),join(app,path));
const manifest=json('docs/pr3-action-manifest.json');assert.equal(manifest.actions.length,19);assert.deepEqual(manifest.actions.map((a:any)=>a.ref),ARBOR_ACTIONS.map(a=>'arbor.'+a.name));
for(const a of ARBOR_ACTIONS){const m=manifest.actions.find((m:any)=>m.name===a.name);assert.deepEqual(m.inputSchema,a.inputSchema);assert.deepEqual(m.outputSchema,a.outputSchema);assert.equal(m.risk,a.risk);assert.deepEqual(m.effect,a.effect);assert.equal(m.actorCommitment,false);}
assert.equal(manifest.actions.find((a:any)=>a.name==='resumeAttempt').risk,'agent');for(const name of ['review','apply','undoApply','export'])assert.equal(manifest.actions.find((a:any)=>a.name===name).risk,'write');
assert.deepEqual(ARBOR_OWNER_REFS,['agents.self','agents.members','agents.status','agents.create','agents.ask','agents.spawn','agents.wait','agents.stop','agents.remove','schema.status']);assert.deepEqual(manifest.actorRequires,['agents.self']);assert.deepEqual(manifest.configuration,{component:'arbor',id:'arbor',config:{stateDirectory:'absolute path outside material'}});
const reachable=new Set<string>();let imports=0;function visit(path:string){path=resolve(path);if(reachable.has(path))return;reachable.add(path);assert.ok(path.startsWith(app+'/'));assert.doesNotMatch(path.slice(app.length),/\/(?:certification|containment|phase7|pr0|fixtures)\//u);for(const m of read(path).matchAll(/(?:from\s*|import\s*)["']([^"']+)["']/gu)){imports++;const ref=m[1]!;if(ref.startsWith('.'))visit(resolve(dirname(path),ref.replace(/\.js$/u,'.ts')));else if(ref.startsWith('pi-fabric'))assert.ok(['pi-fabric','pi-fabric/protocol'].includes(ref),ref);}}
for(const p of ['src/extension.ts','src/package.ts','src/cli/read-only.ts'])visit(p);
const raw=JSON.parse(execFileSync('npm',['pack','--ignore-scripts','--dry-run','--json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']})),pack:any=Array.isArray(raw)?raw[0]:Object.values(raw)[0],packed=new Set<string>(pack.files.map((f:any)=>f.path));for(const p of reachable)assert.ok(packed.has(p.slice(app.length+1)),p);for(const p of packed)assert.doesNotMatch(p,/^(?:dist|\.test-dist|\.runtime|certification|tests)\//u);assert.ok(packed.has('src/material/SourceApply.ts'));assert.ok(packed.has('docs/pr8-recovery-evidence.md'));assert.equal(pkg.pi.skills.length,1);
function lane(name:string,count:number){
 const log=read(join(gate,name+'.log'));assert.equal(read(join(gate,name+'.exit')).trim(),'0',name);
 const totals=(key:string)=>[...log.matchAll(new RegExp('^ℹ '+key+' (\\d+(?:\\.\\d+)?)$','gm'))].map(m=>Number(m[1]));
 const tests=totals('tests');assert.equal(tests.reduce((n,v)=>n+v,0),count,name);assert.deepEqual(totals('pass'),tests,name);
 for(const key of ['fail','cancelled','skipped','todo'])assert.deepEqual(totals(key),tests.map(()=>0),name+': '+key);
 assert.equal(totals('suites').length,tests.length,name);assert.equal(totals('duration_ms').length,tests.length,name+': natural completion');return log;
}
const normal=lane('verified-final-normal',275);assert.deepEqual([...normal.matchAll(/^ℹ tests (\d+)$/gm)].map(m=>Number(m[1])),[5,92,20,42,45,71]);
for(const [name,count] of Object.entries({'repair-pr2-native':8,'final-pr3-native':20,'repair-pr4-native':21,'final-pr5-native':9,'final-pr6-native':21,'final-pr7-native':5,'verified-final-pr8-native':42}))lane(name,count);
assert.equal(read(join(gate,'cleanup-red.exit')).trim(),'1');lane('cleanup-green',1);assert.equal(read(join(gate,'ref-reload-red.exit')).trim(),'1');lane('ref-reload-green',1);
const before=new Set(read(join(gate,'final-native-before.txt')).trim().split('\n')),paths=read(join(gate,'terminal-native-after.txt')).trim().split('\n').filter(p=>!before.has(p));assert.ok(paths.length>100);
let clean=0,guardFailures=0,crashes=0,checkpointFailures=0,maxEventBytes=0,maxTraceBytes=0;const roots=new Set<string>();
for(const p of paths){assert.match(p,/^\.runtime\/pr[2-6]-host\/[^/]+\/[^/]*exit\.json$/);const e=json(p),root=dirname(p);roots.add(root);
 if(p.includes('/exit-guard-')&&!p.endsWith('success.txt.exit.json')){assert.ok(e.code!==0||e.signal);guardFailures++;}
 else if(e.signal==='SIGKILL'){assert.ok(existsSync(join(root,'crash.json')));assert.equal(e.code,null);assert.equal(e.killed,false);assert.ok(e.error);crashes++;}
 else if(p==='.runtime/pr6-host/agent-suite-IvDj5P/exit.json'){assert.deepEqual(e,{code:1,signal:null,killed:true,error:'stdout maxBuffer length exceeded'});checkpointFailures++;} // retained failed 39/40 checkpoint, never a clean exit
 else {assert.deepEqual(e,p.endsWith('/rpc-exit.json')?{code:0,signal:null}:{code:0,signal:null,killed:false,error:null},p);clean++;}
}
assert.equal(guardFailures,6);assert.equal(checkpointFailures,1);assert.ok(crashes>=38);
for(const root of roots){if(!existsSync(join(root,'trace.jsonl')))continue;const text=read(join(root,'trace.jsonl'));maxTraceBytes=Math.max(maxTraceBytes,Buffer.byteLength(text));for(const line of text.trim().split('\n'))maxEventBytes=Math.max(maxEventBytes,Buffer.byteLength(line));}assert.ok(maxEventBytes<4*1048576);
const gapRoots:string[]=[];for(let stage=1;stage<=9;stage++){const g=json(join(gate,`gap-${stage}.json`));assert.equal(g.stage,stage);assert.equal(g.value.stage,stage);assert.match(g.value.error,/Different native/);assert.equal(g.value.denials.length,3);for(const d of g.value.denials)assert.match(d.error,/Different native/);const o=json(join(g.root,'crash-observation.json'));assert.equal(o.exit.signal,'SIGKILL');assert.deepEqual(o.reopenedExit,{code:0,signal:null,killed:false,error:null});assert.ok(o.projectionDigest);gapRoots.push(g.root);}assert.equal(new Set(gapRoots).size,9);
const recoveries=['reservation','attachment','freeze','evaluation','ref'].map(name=>json(join(gate,`recovered-${name}.json`)));for(const r of recoveries){assert.equal(r.value.resumeError,undefined);assert.equal(r.value.p.run.active,0);assert.equal(r.value.p.run.state,'paused');assert.ok(r.value.sameSpec);assert.equal(r.workers,r===recoveries[0]?0:1);}assert.notEqual(recoveries[4].value.before.run.generation,recoveries[4].value.p.run.generation);
const partial=json(join(gate,'native-partial.json')),restart=json(join(gate,'native-restart-parent.json'));for(const r of [partial,restart]){assert.equal(r.value.p.run.attemptsUsed,2);assert.deepEqual(r.value.live,[]);assert.deepEqual(r.value.p.attempts[0],r.value.prior);}assert.equal(partial.value.p.attempts[1].continuation.sourceOid,partial.value.partial.oid);assert.equal(restart.value.p.attempts[1].continuation.sourceOid,restart.value.partial.parent);
for(const mode of ['auto','direction','review','collaborative']){const m=json(join(gate,'native-mode-'+mode+'.json'));assert.ok(m.value.sameSpec&&m.value.sameEpoch);assert.deepEqual(m.value.live,[]);assert.equal(m.value.p.decisions.find((d:any)=>d.decisionId==='pr8-keep')?.status,'measured-keep');}
assert.match(read(join(gate,'repair-red.log')),/^ℹ fail 5$/m);lane('verified-final-target',23);assert.match(read(join(gate,'review-blockers-red.log')),/^ℹ fail 3$/m);lane('review-blockers-green',3);
for(const mode of ['direction','review','collaborative']){const r=json(join(gate,'reload-review-'+mode+'.json'));assert.equal(r.value.resumeError,undefined);assert.equal(r.value.reviewError,undefined);assert.ok(r.value.staleError);assert.equal(r.value.reconciled.run.state,'awaiting_review');assert.notEqual(r.value.before.run.generation,r.value.reconciled.run.generation);assert.deepEqual(r.value.reconciled.attempts,r.value.before.attempts);assert.deepEqual(r.value.reconciled.evaluations,r.value.before.evaluations);assert.equal(r.dialogs.length,1);}
for(const gap of ['journal','receipt']){const r=json(join(gate,'reload-source-'+gap+'.json'));assert.equal(r.value.recoveryError,undefined);assert.equal(r.value.recovered.status,'applied');assert.equal(r.value.undone.status,'applied');const original=JSON.parse(r.value.original),adopted=json(r.value.recovered.value.path);assert.equal(original.state,gap==='journal'?'writing':'applied');assert.deepEqual(adopted.intent,original.intent);assert.equal(adopted.identity,original.identity);assert.equal(adopted.adoptions.length,1);assert.notEqual(adopted.adoptions[0].generation,original.intent.binding.generation);assert.equal(r.dialogs.length,3);}
for(const kind of ['command','agent-suite']){const r=json(join(gate,'reload-material-'+kind+'.json'));assert.equal(r.value.resumeError,undefined);assert.equal(r.value.reviewError,undefined);assert.equal(r.value.receipt.value.state,'awaiting_review');assert.equal(r.value.sameAttempts,true);assert.equal(r.value.sameEvaluations,true);assert.deepEqual(r.value.before.attempts,r.value.reconciled.attempts);assert.deepEqual(r.value.before.evaluations,r.value.reconciled.evaluations);assert.equal(r.value.p.decisions.find((d:any)=>d.decisionId==='material-keep').status,'measured-keep');}
{const r=json(join(gate,'reload-source-new-incumbent.json'));assert.equal(r.value.recoveryError,undefined);assert.equal(r.value.recovered.status,'applied');assert.equal(r.value.undone.status,'applied');assert.notEqual(r.value.before.run.material.incumbent,r.value.advanced.run.material.incumbent);assert.equal(r.value.p.run.material.incumbent,r.value.advanced.run.material.incumbent);const j=json(r.value.recovered.value.path);assert.equal(j.intent.target,r.value.before.run.material.incumbent);for(const d of r.dialogs.slice(1))assert.ok(d.request.title.includes('selected '+j.intent.target));}
for(const name of ['terminal','dangling','continuation-cancel'])assert.equal(read(join(gate,name+'-red.exit')).trim(),'1');assert.equal(read(join(gate,'continuation-red-complete.exit')).trim(),'1');
for(const [name,count] of Object.entries({'terminal-green':3,'terminal-expanded':6,'dangling-green':1,'continuation-green':2,'continuation-native':1,'continuation-cancel-green':1,'continuation-cancel-native':1,'terminal-output-green':1}))lane(name,count);
for(const gap of ['applied','journal','receipt']){const r=json(join(gate,'terminal-source-'+gap+'.json')),v=r.value;assert.equal(v.recoveryError,undefined);assert.equal(v.cancelled.run.state,'cancelled');assert.equal(v.p.run.state,'cancelled');assert.equal(v.p.run.generation,v.cancelled.run.generation);assert.deepEqual(v.p.attempts,v.cancelled.attempts);assert.deepEqual(v.p.evaluations,v.cancelled.evaluations);assert.deepEqual(v.p.run.spec,v.cancelled.run.spec);assert.match(v.resumeError,/terminal|Terminal/);assert.match(v.newApplyError,/original apply intent/);assert.equal(v.undone.status,'applied');const original=JSON.parse(v.original),j=json(join(r.root,'state/runs/research/workspace/source-operations',original.intent.operationId+'.json'));assert.deepEqual(j.intent,original.intent);assert.equal(j.identity,original.identity);assert.notEqual(json(v.undone.value.path).intent.binding.generation,v.p.run.generation);if(gap!=='applied')assert.equal(v.recovered.status,'applied');}
for(const change of ['bytes','mode']){const v=json(join(gate,'terminal-source-newer-'+change+'.json')).value;assert.equal(v.p.run.state,'cancelled');assert.equal(v.recovered.status,'blocked');assert.equal(v.undone.status,'blocked');}
{const r=json(join(gate,'terminal-source-owner-policy-observations.json'));assert.deepEqual(r.observations.map((o:any)=>o.policy),['allow','deny','ask']);for(const o of r.observations){assert.deepEqual(o.exit,{code:0,signal:null,killed:false,error:null});assert.equal(o.value.errors.length,2);for(const e of o.value.errors)assert.match(e,o.policy==='allow'?/Different native/:/denied|approval|permission|requires/i);}}
{const v=json(join(gate,'native-continuation-refine-discard.json')).value;assert.equal(v.refineError,undefined);assert.equal(v.discardError,undefined);assert.equal(v.refined.status,'applied');assert.equal(v.discarded.status,'applied');assert.equal(v.prior.nativeDigest,null);assert.deepEqual(v.p.attempts[0],v.prior);}
{const v=json(join(gate,'native-continuation-cancel.json')).value;assert.equal(v.cancelled.run.state,'cancelled');assert.equal(v.p.run.state,'cancelled');assert.equal(v.p.run.execution,'material-cancelled');assert.match(v.resumeError,/terminal|Terminal/);}
const timing=json('.runtime/pr7-gates/a12.json');assert.ok(timing.ratio<=0.8);for(const r of timing.results){assert.equal(r.warmed.length,3);assert.equal(r.waves.length,4);assert.ok(r.waves.every((w:any)=>w.attemptIds.length===2));if(r.concurrency===2)assert.ok(r.warmed.every((w:any)=>w.overlap>0));}writeFileSync(join(gate,'a12.json'),JSON.stringify(timing,null,2)+'\n');
const changes=[...git('diff','--name-only','-z','HEAD').split('\0'),...git('-C','..','ls-files','--others','--exclude-standard','-z').split('\0')].filter(Boolean);assert.ok(changes.every(p=>p.startsWith('pi-fabric-arbor/')||p==='docs/Arbor/deep-refactoring-plan.md'));assert.ok(changes.every(p=>!/(?:^|\/)(?:node_modules|\.runtime|dist|\.test-dist)(?:\/|$)/u.test(p)));const staged=git('diff','--cached','--name-only').trim().split('\n').filter(Boolean);assert.ok(staged.every(p=>p.startsWith('pi-fabric-arbor/')||p==='docs/Arbor/deep-refactoring-plan.md'));assert.ok(staged.every(p=>!/(?:^|\/)(?:node_modules|\.runtime|dist|\.test-dist)(?:\/|$)/u.test(p)));
const report={scope:'PR8 repaired scoped gate; independent full staged-diff review required before publication; no PR9-13',normalTests:275,targetedTests:23,nativeTests:{pr2:8,pr3:20,pr4:21,pr5:9,pr6:21,pr7:5,pr8:42},publicRefs:19,ownerRequirements:10,publicSkills:1,reachableModules:reachable.size,staticImports:imports,packedFiles:packed.size,nativeExitInventory:{clean,guardFailures,crashes,checkpointFailures,paths},maxEventBytes,maxTraceBytes,gapRoots,a12:{ratio:timing.ratio,serialMedian:timing.results[0].median,parallelMedian:timing.results[1].median}};writeFileSync(join(gate,'audit.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,nativeExitInventory:{clean,guardFailures,crashes,checkpointFailures,paths:paths.length}}));
